import { Continent } from 'src/modules/system/country/entities/country.entity';

export default [
	{
		code: 'ABW',
		name: 'Aruba',
		continent: Continent['North America'],
		region: 'Caribbean',
		surface_area: '193.00',
		indep_year: null,
		population: '103000',
		life_expectancy: '78.4',
		gnp: '828.00',
		gnp_old: '793.00',
		local_name: 'Aruba',
		government_form: 'Nonmetropolitan Territory of The Netherlands',
		head_of_state: 'Beatrix',
		capital: '129',
		code_2: 'AW',
	},
	{
		code: 'AFG',
		name: 'Afghanistan',
		continent: Continent.Asia,
		region: 'Southern and Central Asia',
		surface_area: '652090.00',
		indep_year: '1919',
		population: '22720000',
		life_expectancy: '45.9',
		gnp: '5976.00',
		gnp_old: null,
		local_name: 'Afganistan/Afqanestan',
		government_form: 'Islamic Emirate',
		head_of_state: 'Mohammad Omar',
		capital: '1',
		code_2: 'AF',
	},
	{
		code: 'AGO',
		name: 'Angola',
		continent: Continent.Africa,
		region: 'Central Africa',
		surface_area: '1246700.00',
		indep_year: '1975',
		population: '12878000',
		life_expectancy: '38.3',
		gnp: '6648.00',
		gnp_old: '7984.00',
		local_name: 'Angola',
		government_form: 'Republic',
		head_of_state: 'José Eduardo dos Santos',
		capital: '56',
		code_2: 'AO',
	},
	{
		code: 'AIA',
		name: 'Anguilla',
		continent: Continent['North America'],
		region: 'Caribbean',
		surface_area: '96.00',
		indep_year: null,
		population: '8000',
		life_expectancy: '76.1',
		gnp: '63.20',
		gnp_old: null,
		local_name: 'Anguilla',
		government_form: 'Dependent Territory of the UK',
		head_of_state: 'Elisabeth II',
		capital: '62',
		code_2: 'AI',
	},
	{
		code: 'ALB',
		name: 'Albania',
		continent: Continent.Europe,
		region: 'Southern Europe',
		surface_area: '28748.00',
		indep_year: '1912',
		population: '3401200',
		life_expectancy: '71.6',
		gnp: '3205.00',
		gnp_old: '2500.00',
		local_name: 'Shqipëria',
		government_form: 'Republic',
		head_of_state: 'Rexhep Mejdani',
		capital: '34',
		code_2: 'AL',
	},
	{
		code: 'AND',
		name: 'Andorra',
		continent: Continent.Europe,
		region: 'Southern Europe',
		surface_area: '468.00',
		indep_year: '1278',
		population: '78000',
		life_expectancy: '83.5',
		gnp: '1630.00',
		gnp_old: null,
		local_name: 'Andorra',
		government_form: 'Parliamentary Coprincipality',
		head_of_state: '',
		capital: '55',
		code_2: 'AD',
	},
	{
		code: 'ANT',
		name: 'Netherlands Antilles',
		continent: Continent['North America'],
		region: 'Caribbean',
		surface_area: '800.00',
		indep_year: null,
		population: '217000',
		life_expectancy: '74.7',
		gnp: '1941.00',
		gnp_old: null,
		local_name: 'Nederlandse Antillen',
		government_form: 'Nonmetropolitan Territory of The Netherlands',
		head_of_state: 'Beatrix',
		capital: '33',
		code_2: 'AN',
	},
	{
		code: 'ARE',
		name: 'United Arab Emirates',
		continent: Continent.Asia,
		region: 'Middle East',
		surface_area: '83600.00',
		indep_year: '1971',
		population: '2441000',
		life_expectancy: '74.1',
		gnp: '37966.00',
		gnp_old: '36846.00',
		local_name: 'Al-Imarat al-´Arabiya al-Muttahida',
		government_form: 'Emirate Federation',
		head_of_state: 'Zayid bin Sultan al-Nahayan',
		capital: '65',
		code_2: 'AE',
	},
	{
		code: 'ARG',
		name: 'Argentina',
		continent: Continent['South America'],
		region: 'South America',
		surface_area: '2780400.00',
		indep_year: '1816',
		population: '37032000',
		life_expectancy: '75.1',
		gnp: '340238.00',
		gnp_old: '323310.00',
		local_name: 'Argentina',
		government_form: 'Federal Republic',
		head_of_state: 'Fernando de la Rúa',
		capital: '69',
		code_2: 'AR',
	},
	{
		code: 'ARM',
		name: 'Armenia',
		continent: Continent.Asia,
		region: 'Middle East',
		surface_area: '29800.00',
		indep_year: '1991',
		population: '3520000',
		life_expectancy: '66.4',
		gnp: '1813.00',
		gnp_old: '1627.00',
		local_name: 'Hajastan',
		government_form: 'Republic',
		head_of_state: 'Robert Kotšarjan',
		capital: '126',
		code_2: 'AM',
	},
	{
		code: 'ASM',
		name: 'American Samoa',
		continent: Continent.Oceania,
		region: 'Polynesia',
		surface_area: '199.00',
		indep_year: null,
		population: '68000',
		life_expectancy: '75.1',
		gnp: '334.00',
		gnp_old: null,
		local_name: 'Amerika Samoa',
		government_form: 'US Territory',
		head_of_state: 'George W. Bush',
		capital: '54',
		code_2: 'AS',
	},
	{
		code: 'ATA',
		name: 'Antarctica',
		continent: Continent.Antarctica,
		region: 'Antarctica',
		surface_area: '13120000.00',
		indep_year: null,
		population: '0',
		life_expectancy: null,
		gnp: '0.00',
		gnp_old: null,
		local_name: '–',
		government_form: 'Co-administrated',
		head_of_state: '',
		capital: null,
		code_2: 'AQ',
	},
	{
		code: 'ATF',
		name: 'French Southern territories',
		continent: Continent.Antarctica,
		region: 'Antarctica',
		surface_area: '7780.00',
		indep_year: null,
		population: '0',
		life_expectancy: null,
		gnp: '0.00',
		gnp_old: null,
		local_name: 'Terres australes françaises',
		government_form: 'Nonmetropolitan Territory of France',
		head_of_state: 'Jacques Chirac',
		capital: null,
		code_2: 'TF',
	},
	{
		code: 'ATG',
		name: 'Antigua and Barbuda',
		continent: Continent['North America'],
		region: 'Caribbean',
		surface_area: '442.00',
		indep_year: '1981',
		population: '68000',
		life_expectancy: '70.5',
		gnp: '612.00',
		gnp_old: '584.00',
		local_name: 'Antigua and Barbuda',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Elisabeth II',
		capital: '63',
		code_2: 'AG',
	},
	{
		code: 'AUS',
		name: 'Australia',
		continent: Continent.Oceania,
		region: 'Australia and New Zealand',
		surface_area: '7741220.00',
		indep_year: '1901',
		population: '18886000',
		life_expectancy: '79.8',
		gnp: '351182.00',
		gnp_old: '392911.00',
		local_name: 'Australia',
		government_form: 'Constitutional Monarchy, Federation',
		head_of_state: 'Elisabeth II',
		capital: '135',
		code_2: 'AU',
	},
	{
		code: 'AUT',
		name: 'Austria',
		continent: Continent.Europe,
		region: 'Western Europe',
		surface_area: '83859.00',
		indep_year: '1918',
		population: '8091800',
		life_expectancy: '77.7',
		gnp: '211860.00',
		gnp_old: '206025.00',
		local_name: 'Österreich',
		government_form: 'Federal Republic',
		head_of_state: 'Thomas Klestil',
		capital: '1523',
		code_2: 'AT',
	},
	{
		code: 'AZE',
		name: 'Azerbaijan',
		continent: Continent.Asia,
		region: 'Middle East',
		surface_area: '86600.00',
		indep_year: '1991',
		population: '7734000',
		life_expectancy: '62.9',
		gnp: '4127.00',
		gnp_old: '4100.00',
		local_name: 'Azärbaycan',
		government_form: 'Federal Republic',
		head_of_state: 'Heydär Äliyev',
		capital: '144',
		code_2: 'AZ',
	},
	{
		code: 'BDI',
		name: 'Burundi',
		continent: Continent.Africa,
		region: 'Eastern Africa',
		surface_area: '27834.00',
		indep_year: '1962',
		population: '6695000',
		life_expectancy: '46.2',
		gnp: '903.00',
		gnp_old: '982.00',
		local_name: 'Burundi/Uburundi',
		government_form: 'Republic',
		head_of_state: 'Pierre Buyoya',
		capital: '552',
		code_2: 'BI',
	},
	{
		code: 'BEL',
		name: 'Belgium',
		continent: Continent.Europe,
		region: 'Western Europe',
		surface_area: '30518.00',
		indep_year: '1830',
		population: '10239000',
		life_expectancy: '77.8',
		gnp: '249704.00',
		gnp_old: '243948.00',
		local_name: 'België/Belgique',
		government_form: 'Constitutional Monarchy, Federation',
		head_of_state: 'Albert II',
		capital: '179',
		code_2: 'BE',
	},
	{
		code: 'BEN',
		name: 'Benin',
		continent: Continent.Africa,
		region: 'Western Africa',
		surface_area: '112622.00',
		indep_year: '1960',
		population: '6097000',
		life_expectancy: '50.2',
		gnp: '2357.00',
		gnp_old: '2141.00',
		local_name: 'Bénin',
		government_form: 'Republic',
		head_of_state: 'Mathieu Kérékou',
		capital: '187',
		code_2: 'BJ',
	},
	{
		code: 'BFA',
		name: 'Burkina Faso',
		continent: Continent.Africa,
		region: 'Western Africa',
		surface_area: '274000.00',
		indep_year: '1960',
		population: '11937000',
		life_expectancy: '46.7',
		gnp: '2425.00',
		gnp_old: '2201.00',
		local_name: 'Burkina Faso',
		government_form: 'Republic',
		head_of_state: 'Blaise Compaoré',
		capital: '549',
		code_2: 'BF',
	},
	{
		code: 'BGD',
		name: 'Bangladesh',
		continent: Continent.Asia,
		region: 'Southern and Central Asia',
		surface_area: '143998.00',
		indep_year: '1971',
		population: '129155000',
		life_expectancy: '60.2',
		gnp: '32852.00',
		gnp_old: '31966.00',
		local_name: 'Bangladesh',
		government_form: 'Republic',
		head_of_state: 'Shahabuddin Ahmad',
		capital: '150',
		code_2: 'BD',
	},
	{
		code: 'BGR',
		name: 'Bulgaria',
		continent: Continent.Europe,
		region: 'Eastern Europe',
		surface_area: '110994.00',
		indep_year: '1908',
		population: '8190900',
		life_expectancy: '70.9',
		gnp: '12178.00',
		gnp_old: '10169.00',
		local_name: 'Balgarija',
		government_form: 'Republic',
		head_of_state: 'Petar Stojanov',
		capital: '539',
		code_2: 'BG',
	},
	{
		code: 'BHR',
		name: 'Bahrain',
		continent: Continent.Asia,
		region: 'Middle East',
		surface_area: '694.00',
		indep_year: '1971',
		population: '617000',
		life_expectancy: '73.0',
		gnp: '6366.00',
		gnp_old: '6097.00',
		local_name: 'Al-Bahrayn',
		government_form: 'Monarchy (Emirate)',
		head_of_state: 'Hamad ibn Isa al-Khalifa',
		capital: '149',
		code_2: 'BH',
	},
	{
		code: 'BHS',
		name: 'Bahamas',
		continent: Continent['North America'],
		region: 'Caribbean',
		surface_area: '13878.00',
		indep_year: '1973',
		population: '307000',
		life_expectancy: '71.1',
		gnp: '3527.00',
		gnp_old: '3347.00',
		local_name: 'The Bahamas',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Elisabeth II',
		capital: '148',
		code_2: 'BS',
	},
	{
		code: 'BIH',
		name: 'Bosnia and Herzegovina',
		continent: Continent.Europe,
		region: 'Southern Europe',
		surface_area: '51197.00',
		indep_year: '1992',
		population: '3972000',
		life_expectancy: '71.5',
		gnp: '2841.00',
		gnp_old: null,
		local_name: 'Bosna i Hercegovina',
		government_form: 'Federal Republic',
		head_of_state: 'Ante Jelavic',
		capital: '201',
		code_2: 'BA',
	},
	{
		code: 'BLR',
		name: 'Belarus',
		continent: Continent.Europe,
		region: 'Eastern Europe',
		surface_area: '207600.00',
		indep_year: '1991',
		population: '10236000',
		life_expectancy: '68.0',
		gnp: '13714.00',
		gnp_old: null,
		local_name: 'Belarus',
		government_form: 'Republic',
		head_of_state: 'Aljaksandr Lukašenka',
		capital: '3520',
		code_2: 'BY',
	},
	{
		code: 'BLZ',
		name: 'Belize',
		continent: Continent['North America'],
		region: 'Central America',
		surface_area: '22696.00',
		indep_year: '1981',
		population: '241000',
		life_expectancy: '70.9',
		gnp: '630.00',
		gnp_old: '616.00',
		local_name: 'Belize',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Elisabeth II',
		capital: '185',
		code_2: 'BZ',
	},
	{
		code: 'BMU',
		name: 'Bermuda',
		continent: Continent['North America'],
		region: 'North America',
		surface_area: '53.00',
		indep_year: null,
		population: '65000',
		life_expectancy: '76.9',
		gnp: '2328.00',
		gnp_old: '2190.00',
		local_name: 'Bermuda',
		government_form: 'Dependent Territory of the UK',
		head_of_state: 'Elisabeth II',
		capital: '191',
		code_2: 'BM',
	},
	{
		code: 'BOL',
		name: 'Bolivia',
		continent: Continent['South America'],
		region: 'South America',
		surface_area: '1098581.00',
		indep_year: '1825',
		population: '8329000',
		life_expectancy: '63.7',
		gnp: '8571.00',
		gnp_old: '7967.00',
		local_name: 'Bolivia',
		government_form: 'Republic',
		head_of_state: 'Hugo Bánzer Suárez',
		capital: '194',
		code_2: 'BO',
	},
	{
		code: 'BRA',
		name: 'Brazil',
		continent: Continent['South America'],
		region: 'South America',
		surface_area: '8547403.00',
		indep_year: '1822',
		population: '170115000',
		life_expectancy: '62.9',
		gnp: '776739.00',
		gnp_old: '804108.00',
		local_name: 'Brasil',
		government_form: 'Federal Republic',
		head_of_state: 'Fernando Henrique Cardoso',
		capital: '211',
		code_2: 'BR',
	},
	{
		code: 'BRB',
		name: 'Barbados',
		continent: Continent['North America'],
		region: 'Caribbean',
		surface_area: '430.00',
		indep_year: '1966',
		population: '270000',
		life_expectancy: '73.0',
		gnp: '2223.00',
		gnp_old: '2186.00',
		local_name: 'Barbados',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Elisabeth II',
		capital: '174',
		code_2: 'BB',
	},
	{
		code: 'BRN',
		name: 'Brunei',
		continent: Continent.Asia,
		region: 'Southeast Asia',
		surface_area: '5765.00',
		indep_year: '1984',
		population: '328000',
		life_expectancy: '73.6',
		gnp: '11705.00',
		gnp_old: '12460.00',
		local_name: 'Brunei Darussalam',
		government_form: 'Monarchy (Sultanate)',
		head_of_state: 'Haji Hassan al-Bolkiah',
		capital: '538',
		code_2: 'BN',
	},
	{
		code: 'BTN',
		name: 'Bhutan',
		continent: Continent.Asia,
		region: 'Southern and Central Asia',
		surface_area: '47000.00',
		indep_year: '1910',
		population: '2124000',
		life_expectancy: '52.4',
		gnp: '372.00',
		gnp_old: '383.00',
		local_name: 'Druk-Yul',
		government_form: 'Monarchy',
		head_of_state: 'Jigme Singye Wangchuk',
		capital: '192',
		code_2: 'BT',
	},
	{
		code: 'BVT',
		name: 'Bouvet Island',
		continent: Continent.Antarctica,
		region: 'Antarctica',
		surface_area: '59.00',
		indep_year: null,
		population: '0',
		life_expectancy: null,
		gnp: '0.00',
		gnp_old: null,
		local_name: 'Bouvetøya',
		government_form: 'Dependent Territory of Norway',
		head_of_state: 'Harald V',
		capital: null,
		code_2: 'BV',
	},
	{
		code: 'BWA',
		name: 'Botswana',
		continent: Continent.Africa,
		region: 'Southern Africa',
		surface_area: '581730.00',
		indep_year: '1966',
		population: '1622000',
		life_expectancy: '39.3',
		gnp: '4834.00',
		gnp_old: '4935.00',
		local_name: 'Botswana',
		government_form: 'Republic',
		head_of_state: 'Festus G. Mogae',
		capital: '204',
		code_2: 'BW',
	},
	{
		code: 'CAF',
		name: 'Central African Republic',
		continent: Continent.Africa,
		region: 'Central Africa',
		surface_area: '622984.00',
		indep_year: '1960',
		population: '3615000',
		life_expectancy: '44.0',
		gnp: '1054.00',
		gnp_old: '993.00',
		local_name: 'Centrafrique/Bê-Afrîka',
		government_form: 'Republic',
		head_of_state: 'Ange-Félix Patassé',
		capital: '1889',
		code_2: 'CF',
	},
	{
		code: 'CAN',
		name: 'Canada',
		continent: Continent['North America'],
		region: 'North America',
		surface_area: '9970610.00',
		indep_year: '1867',
		population: '31147000',
		life_expectancy: '79.4',
		gnp: '598862.00',
		gnp_old: '625626.00',
		local_name: 'Canada',
		government_form: 'Constitutional Monarchy, Federation',
		head_of_state: 'Elisabeth II',
		capital: '1822',
		code_2: 'CA',
	},
	{
		code: 'CCK',
		name: 'Cocos (Keeling) Islands',
		continent: Continent.Oceania,
		region: 'Australia and New Zealand',
		surface_area: '14.00',
		indep_year: null,
		population: '600',
		life_expectancy: null,
		gnp: '0.00',
		gnp_old: null,
		local_name: 'Cocos (Keeling) Islands',
		government_form: 'Territory of Australia',
		head_of_state: 'Elisabeth II',
		capital: '2317',
		code_2: 'CC',
	},
	{
		code: 'CHE',
		name: 'Switzerland',
		continent: Continent.Europe,
		region: 'Western Europe',
		surface_area: '41284.00',
		indep_year: '1499',
		population: '7160400',
		life_expectancy: '79.6',
		gnp: '264478.00',
		gnp_old: '256092.00',
		local_name: 'Schweiz/Suisse/Svizzera/Svizra',
		government_form: 'Federation',
		head_of_state: 'Adolf Ogi',
		capital: '3248',
		code_2: 'CH',
	},
	{
		code: 'CHL',
		name: 'Chile',
		continent: Continent['South America'],
		region: 'South America',
		surface_area: '756626.00',
		indep_year: '1810',
		population: '15211000',
		life_expectancy: '75.7',
		gnp: '72949.00',
		gnp_old: '75780.00',
		local_name: 'Chile',
		government_form: 'Republic',
		head_of_state: 'Ricardo Lagos Escobar',
		capital: '554',
		code_2: 'CL',
	},
	{
		code: 'CHN',
		name: 'China',
		continent: Continent.Asia,
		region: 'Eastern Asia',
		surface_area: '9572900.00',
		indep_year: '-1523',
		population: '1277558000',
		life_expectancy: '71.4',
		gnp: '982268.00',
		gnp_old: '917719.00',
		local_name: 'Zhongquo',
		government_form: "People'sRepublic",
		head_of_state: 'Jiang Zemin',
		capital: '1891',
		code_2: 'CN',
	},
	{
		code: 'CIV',
		name: 'Côte d’Ivoire',
		continent: Continent.Africa,
		region: 'Western Africa',
		surface_area: '322463.00',
		indep_year: '1960',
		population: '14786000',
		life_expectancy: '45.2',
		gnp: '11345.00',
		gnp_old: '10285.00',
		local_name: 'Côte d’Ivoire',
		government_form: 'Republic',
		head_of_state: 'Laurent Gbagbo',
		capital: '2814',
		code_2: 'CI',
	},
	{
		code: 'CMR',
		name: 'Cameroon',
		continent: Continent.Africa,
		region: 'Central Africa',
		surface_area: '475442.00',
		indep_year: '1960',
		population: '15085000',
		life_expectancy: '54.8',
		gnp: '9174.00',
		gnp_old: '8596.00',
		local_name: 'Cameroun/Cameroon',
		government_form: 'Republic',
		head_of_state: 'Paul Biya',
		capital: '1804',
		code_2: 'CM',
	},
	{
		code: 'COD',
		name: 'Congo, The Democratic Republic of the',
		continent: Continent.Africa,
		region: 'Central Africa',
		surface_area: '2344858.00',
		indep_year: '1960',
		population: '51654000',
		life_expectancy: '48.8',
		gnp: '6964.00',
		gnp_old: '2474.00',
		local_name: 'République Démocratique du Congo',
		government_form: 'Republic',
		head_of_state: 'Joseph Kabila',
		capital: '2298',
		code_2: 'CD',
	},
	{
		code: 'COG',
		name: 'Congo',
		continent: Continent.Africa,
		region: 'Central Africa',
		surface_area: '342000.00',
		indep_year: '1960',
		population: '2943000',
		life_expectancy: '47.4',
		gnp: '2108.00',
		gnp_old: '2287.00',
		local_name: 'Congo',
		government_form: 'Republic',
		head_of_state: 'Denis Sassou-Nguesso',
		capital: '2296',
		code_2: 'CG',
	},
	{
		code: 'COK',
		name: 'Cook Islands',
		continent: Continent.Oceania,
		region: 'Polynesia',
		surface_area: '236.00',
		indep_year: null,
		population: '20000',
		life_expectancy: '71.1',
		gnp: '100.00',
		gnp_old: null,
		local_name: 'The Cook Islands',
		government_form: 'Nonmetropolitan Territory of New Zealand',
		head_of_state: 'Elisabeth II',
		capital: '583',
		code_2: 'CK',
	},
	{
		code: 'COL',
		name: 'Colombia',
		continent: Continent['South America'],
		region: 'South America',
		surface_area: '1138914.00',
		indep_year: '1810',
		population: '42321000',
		life_expectancy: '70.3',
		gnp: '102896.00',
		gnp_old: '105116.00',
		local_name: 'Colombia',
		government_form: 'Republic',
		head_of_state: 'Andrés Pastrana Arango',
		capital: '2257',
		code_2: 'CO',
	},
	{
		code: 'COM',
		name: 'Comoros',
		continent: Continent.Africa,
		region: 'Eastern Africa',
		surface_area: '1862.00',
		indep_year: '1975',
		population: '578000',
		life_expectancy: '60.0',
		gnp: '4401.00',
		gnp_old: '4361.00',
		local_name: 'Komori/Comores',
		government_form: 'Republic',
		head_of_state: 'Azali Assoumani',
		capital: '2295',
		code_2: 'KM',
	},
	{
		code: 'CPV',
		name: 'Cape Verde',
		continent: Continent.Africa,
		region: 'Western Africa',
		surface_area: '4033.00',
		indep_year: '1975',
		population: '428000',
		life_expectancy: '68.9',
		gnp: '435.00',
		gnp_old: '420.00',
		local_name: 'Cabo Verde',
		government_form: 'Republic',
		head_of_state: 'António Mascarenhas Monteiro',
		capital: '1859',
		code_2: 'CV',
	},
	{
		code: 'CRI',
		name: 'Costa Rica',
		continent: Continent['North America'],
		region: 'Central America',
		surface_area: '51100.00',
		indep_year: '1821',
		population: '4023000',
		life_expectancy: '75.8',
		gnp: '10226.00',
		gnp_old: '9757.00',
		local_name: 'Costa Rica',
		government_form: 'Republic',
		head_of_state: 'Miguel Ángel Rodríguez Echeverría',
		capital: '584',
		code_2: 'CR',
	},
	{
		code: 'CUB',
		name: 'Cuba',
		continent: Continent['North America'],
		region: 'Caribbean',
		surface_area: '110861.00',
		indep_year: '1902',
		population: '11201000',
		life_expectancy: '76.2',
		gnp: '17843.00',
		gnp_old: '18862.00',
		local_name: 'Cuba',
		government_form: 'Socialistic Republic',
		head_of_state: 'Fidel Castro Ruz',
		capital: '2413',
		code_2: 'CU',
	},
	{
		code: 'CXR',
		name: 'Christmas Island',
		continent: Continent.Oceania,
		region: 'Australia and New Zealand',
		surface_area: '135.00',
		indep_year: null,
		population: '2500',
		life_expectancy: null,
		gnp: '0.00',
		gnp_old: null,
		local_name: 'Christmas Island',
		government_form: 'Territory of Australia',
		head_of_state: 'Elisabeth II',
		capital: '1791',
		code_2: 'CX',
	},
	{
		code: 'CYM',
		name: 'Cayman Islands',
		continent: Continent['North America'],
		region: 'Caribbean',
		surface_area: '264.00',
		indep_year: null,
		population: '38000',
		life_expectancy: '78.9',
		gnp: '1263.00',
		gnp_old: '1186.00',
		local_name: 'Cayman Islands',
		government_form: 'Dependent Territory of the UK',
		head_of_state: 'Elisabeth II',
		capital: '553',
		code_2: 'KY',
	},
	{
		code: 'CYP',
		name: 'Cyprus',
		continent: Continent.Asia,
		region: 'Middle East',
		surface_area: '9251.00',
		indep_year: '1960',
		population: '754700',
		life_expectancy: '76.7',
		gnp: '9333.00',
		gnp_old: '8246.00',
		local_name: 'Kýpros/Kibris',
		government_form: 'Republic',
		head_of_state: 'Glafkos Klerides',
		capital: '2430',
		code_2: 'CY',
	},
	{
		code: 'CZE',
		name: 'Czech Republic',
		continent: Continent.Europe,
		region: 'Eastern Europe',
		surface_area: '78866.00',
		indep_year: '1993',
		population: '10278100',
		life_expectancy: '74.5',
		gnp: '55017.00',
		gnp_old: '52037.00',
		local_name: '¸esko',
		government_form: 'Republic',
		head_of_state: 'Václav Havel',
		capital: '3339',
		code_2: 'CZ',
	},
	{
		code: 'DEU',
		name: 'Germany',
		continent: Continent.Europe,
		region: 'Western Europe',
		surface_area: '357022.00',
		indep_year: '1955',
		population: '82164700',
		life_expectancy: '77.4',
		gnp: '2133367.00',
		gnp_old: '2102826.00',
		local_name: 'Deutschland',
		government_form: 'Federal Republic',
		head_of_state: 'Johannes Rau',
		capital: '3068',
		code_2: 'DE',
	},
	{
		code: 'DJI',
		name: 'Djibouti',
		continent: Continent.Africa,
		region: 'Eastern Africa',
		surface_area: '23200.00',
		indep_year: '1977',
		population: '638000',
		life_expectancy: '50.8',
		gnp: '382.00',
		gnp_old: '373.00',
		local_name: 'Djibouti/Jibuti',
		government_form: 'Republic',
		head_of_state: 'Ismail Omar Guelleh',
		capital: '585',
		code_2: 'DJ',
	},
	{
		code: 'DMA',
		name: 'Dominica',
		continent: Continent['North America'],
		region: 'Caribbean',
		surface_area: '751.00',
		indep_year: '1978',
		population: '71000',
		life_expectancy: '73.4',
		gnp: '256.00',
		gnp_old: '243.00',
		local_name: 'Dominica',
		government_form: 'Republic',
		head_of_state: 'Vernon Shaw',
		capital: '586',
		code_2: 'DM',
	},
	{
		code: 'DNK',
		name: 'Denmark',
		continent: Continent.Europe,
		region: 'Nordic Countries',
		surface_area: '43094.00',
		indep_year: '800',
		population: '5330000',
		life_expectancy: '76.5',
		gnp: '174099.00',
		gnp_old: '169264.00',
		local_name: 'Danmark',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Margrethe II',
		capital: '3315',
		code_2: 'DK',
	},
	{
		code: 'DOM',
		name: 'Dominican Republic',
		continent: Continent['North America'],
		region: 'Caribbean',
		surface_area: '48511.00',
		indep_year: '1844',
		population: '8495000',
		life_expectancy: '73.2',
		gnp: '15846.00',
		gnp_old: '15076.00',
		local_name: 'República Dominicana',
		government_form: 'Republic',
		head_of_state: 'Hipólito Mejía Domínguez',
		capital: '587',
		code_2: 'DO',
	},
	{
		code: 'DZA',
		name: 'Algeria',
		continent: Continent.Africa,
		region: 'Northern Africa',
		surface_area: '2381741.00',
		indep_year: '1962',
		population: '31471000',
		life_expectancy: '69.7',
		gnp: '49982.00',
		gnp_old: '46966.00',
		local_name: 'Al-Jaza’ir/Algérie',
		government_form: 'Republic',
		head_of_state: 'Abdelaziz Bouteflika',
		capital: '35',
		code_2: 'DZ',
	},
	{
		code: 'ECU',
		name: 'Ecuador',
		continent: Continent['South America'],
		region: 'South America',
		surface_area: '283561.00',
		indep_year: '1822',
		population: '12646000',
		life_expectancy: '71.1',
		gnp: '19770.00',
		gnp_old: '19769.00',
		local_name: 'Ecuador',
		government_form: 'Republic',
		head_of_state: 'Gustavo Noboa Bejarano',
		capital: '594',
		code_2: 'EC',
	},
	{
		code: 'EGY',
		name: 'Egypt',
		continent: Continent.Africa,
		region: 'Northern Africa',
		surface_area: '1001449.00',
		indep_year: '1922',
		population: '68470000',
		life_expectancy: '63.3',
		gnp: '82710.00',
		gnp_old: '75617.00',
		local_name: 'Misr',
		government_form: 'Republic',
		head_of_state: 'Hosni Mubarak',
		capital: '608',
		code_2: 'EG',
	},
	{
		code: 'ERI',
		name: 'Eritrea',
		continent: Continent.Africa,
		region: 'Eastern Africa',
		surface_area: '117600.00',
		indep_year: '1993',
		population: '3850000',
		life_expectancy: '55.8',
		gnp: '650.00',
		gnp_old: '755.00',
		local_name: 'Ertra',
		government_form: 'Republic',
		head_of_state: 'Isayas Afewerki [Isaias Afwerki]',
		capital: '652',
		code_2: 'ER',
	},
	{
		code: 'ESH',
		name: 'Western Sahara',
		continent: Continent.Africa,
		region: 'Northern Africa',
		surface_area: '266000.00',
		indep_year: null,
		population: '293000',
		life_expectancy: '49.8',
		gnp: '60.00',
		gnp_old: null,
		local_name: 'As-Sahrawiya',
		government_form: 'Occupied by Marocco',
		head_of_state: 'Mohammed Abdel Aziz',
		capital: '2453',
		code_2: 'EH',
	},
	{
		code: 'ESP',
		name: 'Spain',
		continent: Continent.Europe,
		region: 'Southern Europe',
		surface_area: '505992.00',
		indep_year: '1492',
		population: '39441700',
		life_expectancy: '78.8',
		gnp: '553233.00',
		gnp_old: '532031.00',
		local_name: 'España',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Juan Carlos I',
		capital: '653',
		code_2: 'ES',
	},
	{
		code: 'EST',
		name: 'Estonia',
		continent: Continent.Europe,
		region: 'Baltic Countries',
		surface_area: '45227.00',
		indep_year: '1991',
		population: '1439200',
		life_expectancy: '69.5',
		gnp: '5328.00',
		gnp_old: '3371.00',
		local_name: 'Eesti',
		government_form: 'Republic',
		head_of_state: 'Lennart Meri',
		capital: '3791',
		code_2: 'EE',
	},
	{
		code: 'ETH',
		name: 'Ethiopia',
		continent: Continent.Africa,
		region: 'Eastern Africa',
		surface_area: '1104300.00',
		indep_year: '-1000',
		population: '62565000',
		life_expectancy: '45.2',
		gnp: '6353.00',
		gnp_old: '6180.00',
		local_name: 'YeItyop´iya',
		government_form: 'Republic',
		head_of_state: 'Negasso Gidada',
		capital: '756',
		code_2: 'ET',
	},
	{
		code: 'FIN',
		name: 'Finland',
		continent: Continent.Europe,
		region: 'Nordic Countries',
		surface_area: '338145.00',
		indep_year: '1917',
		population: '5171300',
		life_expectancy: '77.4',
		gnp: '121914.00',
		gnp_old: '119833.00',
		local_name: 'Suomi',
		government_form: 'Republic',
		head_of_state: 'Tarja Halonen',
		capital: '3236',
		code_2: 'FI',
	},
	{
		code: 'FJI',
		name: 'Fiji Islands',
		continent: Continent.Oceania,
		region: 'Melanesia',
		surface_area: '18274.00',
		indep_year: '1970',
		population: '817000',
		life_expectancy: '67.9',
		gnp: '1536.00',
		gnp_old: '2149.00',
		local_name: 'Fiji Islands',
		government_form: 'Republic',
		head_of_state: 'Josefa Iloilo',
		capital: '764',
		code_2: 'FJ',
	},
	{
		code: 'FLK',
		name: 'Falkland Islands',
		continent: Continent['South America'],
		region: 'South America',
		surface_area: '12173.00',
		indep_year: null,
		population: '2000',
		life_expectancy: null,
		gnp: '0.00',
		gnp_old: null,
		local_name: 'Falkland Islands',
		government_form: 'Dependent Territory of the UK',
		head_of_state: 'Elisabeth II',
		capital: '763',
		code_2: 'FK',
	},
	{
		code: 'FRA',
		name: 'France',
		continent: Continent.Europe,
		region: 'Western Europe',
		surface_area: '551500.00',
		indep_year: '843',
		population: '59225700',
		life_expectancy: '78.8',
		gnp: '1424285.00',
		gnp_old: '1392448.00',
		local_name: 'France',
		government_form: 'Republic',
		head_of_state: 'Jacques Chirac',
		capital: '2974',
		code_2: 'FR',
	},
	{
		code: 'FRO',
		name: 'Faroe Islands',
		continent: Continent.Europe,
		region: 'Nordic Countries',
		surface_area: '1399.00',
		indep_year: null,
		population: '43000',
		life_expectancy: '78.4',
		gnp: '0.00',
		gnp_old: null,
		local_name: 'Føroyar',
		government_form: 'Part of Denmark',
		head_of_state: 'Margrethe II',
		capital: '901',
		code_2: 'FO',
	},
	{
		code: 'FSM',
		name: 'Micronesia, Federated States of',
		continent: Continent.Oceania,
		region: 'Micronesia',
		surface_area: '702.00',
		indep_year: '1990',
		population: '119000',
		life_expectancy: '68.6',
		gnp: '212.00',
		gnp_old: null,
		local_name: 'Micronesia',
		government_form: 'Federal Republic',
		head_of_state: 'Leo A. Falcam',
		capital: '2689',
		code_2: 'FM',
	},
	{
		code: 'GAB',
		name: 'Gabon',
		continent: Continent.Africa,
		region: 'Central Africa',
		surface_area: '267668.00',
		indep_year: '1960',
		population: '1226000',
		life_expectancy: '50.1',
		gnp: '5493.00',
		gnp_old: '5279.00',
		local_name: 'Le Gabon',
		government_form: 'Republic',
		head_of_state: 'Omar Bongo',
		capital: '902',
		code_2: 'GA',
	},
	{
		code: 'GBR',
		name: 'United Kingdom',
		continent: Continent.Europe,
		region: 'British Islands',
		surface_area: '242900.00',
		indep_year: '1066',
		population: '59623400',
		life_expectancy: '77.7',
		gnp: '1378330.00',
		gnp_old: '1296830.00',
		local_name: 'United Kingdom',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Elisabeth II',
		capital: '456',
		code_2: 'GB',
	},
	{
		code: 'GEO',
		name: 'Georgia',
		continent: Continent.Asia,
		region: 'Middle East',
		surface_area: '69700.00',
		indep_year: '1991',
		population: '4968000',
		life_expectancy: '64.5',
		gnp: '6064.00',
		gnp_old: '5924.00',
		local_name: 'Sakartvelo',
		government_form: 'Republic',
		head_of_state: 'Eduard Ševardnadze',
		capital: '905',
		code_2: 'GE',
	},
	{
		code: 'GHA',
		name: 'Ghana',
		continent: Continent.Africa,
		region: 'Western Africa',
		surface_area: '238533.00',
		indep_year: '1957',
		population: '20212000',
		life_expectancy: '57.4',
		gnp: '7137.00',
		gnp_old: '6884.00',
		local_name: 'Ghana',
		government_form: 'Republic',
		head_of_state: 'John Kufuor',
		capital: '910',
		code_2: 'GH',
	},
	{
		code: 'GIB',
		name: 'Gibraltar',
		continent: Continent.Europe,
		region: 'Southern Europe',
		surface_area: '6.00',
		indep_year: null,
		population: '25000',
		life_expectancy: '79.0',
		gnp: '258.00',
		gnp_old: null,
		local_name: 'Gibraltar',
		government_form: 'Dependent Territory of the UK',
		head_of_state: 'Elisabeth II',
		capital: '915',
		code_2: 'GI',
	},
	{
		code: 'GIN',
		name: 'Guinea',
		continent: Continent.Africa,
		region: 'Western Africa',
		surface_area: '245857.00',
		indep_year: '1958',
		population: '7430000',
		life_expectancy: '45.6',
		gnp: '2352.00',
		gnp_old: '2383.00',
		local_name: 'Guinée',
		government_form: 'Republic',
		head_of_state: 'Lansana Conté',
		capital: '926',
		code_2: 'GN',
	},
	{
		code: 'GLP',
		name: 'Guadeloupe',
		continent: Continent['North America'],
		region: 'Caribbean',
		surface_area: '1705.00',
		indep_year: null,
		population: '456000',
		life_expectancy: '77.0',
		gnp: '3501.00',
		gnp_old: null,
		local_name: 'Guadeloupe',
		government_form: 'Overseas Department of France',
		head_of_state: 'Jacques Chirac',
		capital: '919',
		code_2: 'GP',
	},
	{
		code: 'GMB',
		name: 'Gambia',
		continent: Continent.Africa,
		region: 'Western Africa',
		surface_area: '11295.00',
		indep_year: '1965',
		population: '1305000',
		life_expectancy: '53.2',
		gnp: '320.00',
		gnp_old: '325.00',
		local_name: 'The Gambia',
		government_form: 'Republic',
		head_of_state: 'Yahya Jammeh',
		capital: '904',
		code_2: 'GM',
	},
	{
		code: 'GNB',
		name: 'Guinea-Bissau',
		continent: Continent.Africa,
		region: 'Western Africa',
		surface_area: '36125.00',
		indep_year: '1974',
		population: '1213000',
		life_expectancy: '49.0',
		gnp: '293.00',
		gnp_old: '272.00',
		local_name: 'Guiné-Bissau',
		government_form: 'Republic',
		head_of_state: 'Kumba Ialá',
		capital: '927',
		code_2: 'GW',
	},
	{
		code: 'GNQ',
		name: 'Equatorial Guinea',
		continent: Continent.Africa,
		region: 'Central Africa',
		surface_area: '28051.00',
		indep_year: '1968',
		population: '453000',
		life_expectancy: '53.6',
		gnp: '283.00',
		gnp_old: '542.00',
		local_name: 'Guinea Ecuatorial',
		government_form: 'Republic',
		head_of_state: 'Teodoro Obiang Nguema Mbasogo',
		capital: '2972',
		code_2: 'GQ',
	},
	{
		code: 'GRC',
		name: 'Greece',
		continent: Continent.Europe,
		region: 'Southern Europe',
		surface_area: '131626.00',
		indep_year: '1830',
		population: '10545700',
		life_expectancy: '78.4',
		gnp: '120724.00',
		gnp_old: '119946.00',
		local_name: 'Elláda',
		government_form: 'Republic',
		head_of_state: 'Kostis Stefanopoulos',
		capital: '2401',
		code_2: 'GR',
	},
	{
		code: 'GRD',
		name: 'Grenada',
		continent: Continent['North America'],
		region: 'Caribbean',
		surface_area: '344.00',
		indep_year: '1974',
		population: '94000',
		life_expectancy: '64.5',
		gnp: '318.00',
		gnp_old: null,
		local_name: 'Grenada',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Elisabeth II',
		capital: '916',
		code_2: 'GD',
	},
	{
		code: 'GRL',
		name: 'Greenland',
		continent: Continent['North America'],
		region: 'North America',
		surface_area: '2166090.00',
		indep_year: null,
		population: '56000',
		life_expectancy: '68.1',
		gnp: '0.00',
		gnp_old: null,
		local_name: 'Kalaallit Nunaat/Grønland',
		government_form: 'Part of Denmark',
		head_of_state: 'Margrethe II',
		capital: '917',
		code_2: 'GL',
	},
	{
		code: 'GTM',
		name: 'Guatemala',
		continent: Continent['North America'],
		region: 'Central America',
		surface_area: '108889.00',
		indep_year: '1821',
		population: '11385000',
		life_expectancy: '66.2',
		gnp: '19008.00',
		gnp_old: '17797.00',
		local_name: 'Guatemala',
		government_form: 'Republic',
		head_of_state: 'Alfonso Portillo Cabrera',
		capital: '922',
		code_2: 'GT',
	},
	{
		code: 'GUF',
		name: 'French Guiana',
		continent: Continent['South America'],
		region: 'South America',
		surface_area: '90000.00',
		indep_year: null,
		population: '181000',
		life_expectancy: '76.1',
		gnp: '681.00',
		gnp_old: null,
		local_name: 'Guyane française',
		government_form: 'Overseas Department of France',
		head_of_state: 'Jacques Chirac',
		capital: '3014',
		code_2: 'GF',
	},
	{
		code: 'GUM',
		name: 'Guam',
		continent: Continent.Oceania,
		region: 'Micronesia',
		surface_area: '549.00',
		indep_year: null,
		population: '168000',
		life_expectancy: '77.8',
		gnp: '1197.00',
		gnp_old: '1136.00',
		local_name: 'Guam',
		government_form: 'US Territory',
		head_of_state: 'George W. Bush',
		capital: '921',
		code_2: 'GU',
	},
	{
		code: 'GUY',
		name: 'Guyana',
		continent: Continent['South America'],
		region: 'South America',
		surface_area: '214969.00',
		indep_year: '1966',
		population: '861000',
		life_expectancy: '64.0',
		gnp: '722.00',
		gnp_old: '743.00',
		local_name: 'Guyana',
		government_form: 'Republic',
		head_of_state: 'Bharrat Jagdeo',
		capital: '928',
		code_2: 'GY',
	},
	{
		code: 'HKG',
		name: 'Hong Kong',
		continent: Continent.Asia,
		region: 'Eastern Asia',
		surface_area: '1075.00',
		indep_year: null,
		population: '6782000',
		life_expectancy: '79.5',
		gnp: '166448.00',
		gnp_old: '173610.00',
		local_name: 'Xianggang/Hong Kong',
		government_form: 'Special Administrative Region of China',
		head_of_state: 'Jiang Zemin',
		capital: '937',
		code_2: 'HK',
	},
	{
		code: 'HMD',
		name: 'Heard Island and McDonald Islands',
		continent: Continent.Antarctica,
		region: 'Antarctica',
		surface_area: '359.00',
		indep_year: null,
		population: '0',
		life_expectancy: null,
		gnp: '0.00',
		gnp_old: null,
		local_name: 'Heard and McDonald Islands',
		government_form: 'Territory of Australia',
		head_of_state: 'Elisabeth II',
		capital: null,
		code_2: 'HM',
	},
	{
		code: 'HND',
		name: 'Honduras',
		continent: Continent['North America'],
		region: 'Central America',
		surface_area: '112088.00',
		indep_year: '1838',
		population: '6485000',
		life_expectancy: '69.9',
		gnp: '5333.00',
		gnp_old: '4697.00',
		local_name: 'Honduras',
		government_form: 'Republic',
		head_of_state: 'Carlos Roberto Flores Facussé',
		capital: '933',
		code_2: 'HN',
	},
	{
		code: 'HRV',
		name: 'Croatia',
		continent: Continent.Europe,
		region: 'Southern Europe',
		surface_area: '56538.00',
		indep_year: '1991',
		population: '4473000',
		life_expectancy: '73.7',
		gnp: '20208.00',
		gnp_old: '19300.00',
		local_name: 'Hrvatska',
		government_form: 'Republic',
		head_of_state: 'Štipe Mesic',
		capital: '2409',
		code_2: 'HR',
	},
	{
		code: 'HTI',
		name: 'Haiti',
		continent: Continent['North America'],
		region: 'Caribbean',
		surface_area: '27750.00',
		indep_year: '1804',
		population: '8222000',
		life_expectancy: '49.2',
		gnp: '3459.00',
		gnp_old: '3107.00',
		local_name: 'Haïti/Dayti',
		government_form: 'Republic',
		head_of_state: 'Jean-Bertrand Aristide',
		capital: '929',
		code_2: 'HT',
	},
	{
		code: 'HUN',
		name: 'Hungary',
		continent: Continent.Europe,
		region: 'Eastern Europe',
		surface_area: '93030.00',
		indep_year: '1918',
		population: '10043200',
		life_expectancy: '71.4',
		gnp: '48267.00',
		gnp_old: '45914.00',
		local_name: 'Magyarország',
		government_form: 'Republic',
		head_of_state: 'Ferenc Mádl',
		capital: '3483',
		code_2: 'HU',
	},
	{
		code: 'IDN',
		name: 'Indonesia',
		continent: Continent.Asia,
		region: 'Southeast Asia',
		surface_area: '1904569.00',
		indep_year: '1945',
		population: '212107000',
		life_expectancy: '68.0',
		gnp: '84982.00',
		gnp_old: '215002.00',
		local_name: 'Indonesia',
		government_form: 'Republic',
		head_of_state: 'Abdurrahman Wahid',
		capital: '939',
		code_2: 'ID',
	},
	{
		code: 'IND',
		name: 'India',
		continent: Continent.Asia,
		region: 'Southern and Central Asia',
		surface_area: '3287263.00',
		indep_year: '1947',
		population: '1013662000',
		life_expectancy: '62.5',
		gnp: '447114.00',
		gnp_old: '430572.00',
		local_name: 'Bharat/India',
		government_form: 'Federal Republic',
		head_of_state: 'Kocheril Raman Narayanan',
		capital: '1109',
		code_2: 'IN',
	},
	{
		code: 'IOT',
		name: 'British Indian Ocean Territory',
		continent: Continent.Africa,
		region: 'Eastern Africa',
		surface_area: '78.00',
		indep_year: null,
		population: '0',
		life_expectancy: null,
		gnp: '0.00',
		gnp_old: null,
		local_name: 'British Indian Ocean Territory',
		government_form: 'Dependent Territory of the UK',
		head_of_state: 'Elisabeth II',
		capital: null,
		code_2: 'IO',
	},
	{
		code: 'IRL',
		name: 'Ireland',
		continent: Continent.Europe,
		region: 'British Islands',
		surface_area: '70273.00',
		indep_year: '1921',
		population: '3775100',
		life_expectancy: '76.8',
		gnp: '75921.00',
		gnp_old: '73132.00',
		local_name: 'Ireland/Éire',
		government_form: 'Republic',
		head_of_state: 'Mary McAleese',
		capital: '1447',
		code_2: 'IE',
	},
	{
		code: 'IRN',
		name: 'Iran',
		continent: Continent.Asia,
		region: 'Southern and Central Asia',
		surface_area: '1648195.00',
		indep_year: '1906',
		population: '67702000',
		life_expectancy: '69.7',
		gnp: '195746.00',
		gnp_old: '160151.00',
		local_name: 'Iran',
		government_form: 'Islamic Republic',
		head_of_state: 'Ali Mohammad Khatami-Ardakani',
		capital: '1380',
		code_2: 'IR',
	},
	{
		code: 'IRQ',
		name: 'Iraq',
		continent: Continent.Asia,
		region: 'Middle East',
		surface_area: '438317.00',
		indep_year: '1932',
		population: '23115000',
		life_expectancy: '66.5',
		gnp: '11500.00',
		gnp_old: null,
		local_name: 'Al-´Iraq',
		government_form: 'Republic',
		head_of_state: 'Saddam Hussein al-Takriti',
		capital: '1365',
		code_2: 'IQ',
	},
	{
		code: 'ISL',
		name: 'Iceland',
		continent: Continent.Europe,
		region: 'Nordic Countries',
		surface_area: '103000.00',
		indep_year: '1944',
		population: '279000',
		life_expectancy: '79.4',
		gnp: '8255.00',
		gnp_old: '7474.00',
		local_name: 'Ísland',
		government_form: 'Republic',
		head_of_state: 'Ólafur Ragnar Grímsson',
		capital: '1449',
		code_2: 'IS',
	},
	{
		code: 'ISR',
		name: 'Israel',
		continent: Continent.Asia,
		region: 'Middle East',
		surface_area: '21056.00',
		indep_year: '1948',
		population: '6217000',
		life_expectancy: '78.6',
		gnp: '97477.00',
		gnp_old: '98577.00',
		local_name: 'Yisra’el/Isra’il',
		government_form: 'Republic',
		head_of_state: 'Moshe Katzav',
		capital: '1450',
		code_2: 'IL',
	},
	{
		code: 'ITA',
		name: 'Italy',
		continent: Continent.Europe,
		region: 'Southern Europe',
		surface_area: '301316.00',
		indep_year: '1861',
		population: '57680000',
		life_expectancy: '79.0',
		gnp: '1161755.00',
		gnp_old: '1145372.00',
		local_name: 'Italia',
		government_form: 'Republic',
		head_of_state: 'Carlo Azeglio Ciampi',
		capital: '1464',
		code_2: 'IT',
	},
	{
		code: 'JAM',
		name: 'Jamaica',
		continent: Continent['North America'],
		region: 'Caribbean',
		surface_area: '10990.00',
		indep_year: '1962',
		population: '2583000',
		life_expectancy: '75.2',
		gnp: '6871.00',
		gnp_old: '6722.00',
		local_name: 'Jamaica',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Elisabeth II',
		capital: '1530',
		code_2: 'JM',
	},
	{
		code: 'JOR',
		name: 'Jordan',
		continent: Continent.Asia,
		region: 'Middle East',
		surface_area: '88946.00',
		indep_year: '1946',
		population: '5083000',
		life_expectancy: '77.4',
		gnp: '7526.00',
		gnp_old: '7051.00',
		local_name: 'Al-Urdunn',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Abdullah II',
		capital: '1786',
		code_2: 'JO',
	},
	{
		code: 'JPN',
		name: 'Japan',
		continent: Continent.Asia,
		region: 'Eastern Asia',
		surface_area: '377829.00',
		indep_year: '-660',
		population: '126714000',
		life_expectancy: '80.7',
		gnp: '3787042.00',
		gnp_old: '4192638.00',
		local_name: 'Nihon/Nippon',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Akihito',
		capital: '1532',
		code_2: 'JP',
	},
	{
		code: 'KAZ',
		name: 'Kazakstan',
		continent: Continent.Asia,
		region: 'Southern and Central Asia',
		surface_area: '2724900.00',
		indep_year: '1991',
		population: '16223000',
		life_expectancy: '63.2',
		gnp: '24375.00',
		gnp_old: '23383.00',
		local_name: 'Qazaqstan',
		government_form: 'Republic',
		head_of_state: 'Nursultan Nazarbajev',
		capital: '1864',
		code_2: 'KZ',
	},
	{
		code: 'KEN',
		name: 'Kenya',
		continent: Continent.Africa,
		region: 'Eastern Africa',
		surface_area: '580367.00',
		indep_year: '1963',
		population: '30080000',
		life_expectancy: '48.0',
		gnp: '9217.00',
		gnp_old: '10241.00',
		local_name: 'Kenya',
		government_form: 'Republic',
		head_of_state: 'Daniel arap Moi',
		capital: '1881',
		code_2: 'KE',
	},
	{
		code: 'KGZ',
		name: 'Kyrgyzstan',
		continent: Continent.Asia,
		region: 'Southern and Central Asia',
		surface_area: '199900.00',
		indep_year: '1991',
		population: '4699000',
		life_expectancy: '63.4',
		gnp: '1626.00',
		gnp_old: '1767.00',
		local_name: 'Kyrgyzstan',
		government_form: 'Republic',
		head_of_state: 'Askar Akajev',
		capital: '2253',
		code_2: 'KG',
	},
	{
		code: 'KHM',
		name: 'Cambodia',
		continent: Continent.Asia,
		region: 'Southeast Asia',
		surface_area: '181035.00',
		indep_year: '1953',
		population: '11168000',
		life_expectancy: '56.5',
		gnp: '5121.00',
		gnp_old: '5670.00',
		local_name: 'Kâmpuchéa',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Norodom Sihanouk',
		capital: '1800',
		code_2: 'KH',
	},
	{
		code: 'KIR',
		name: 'Kiribati',
		continent: Continent.Oceania,
		region: 'Micronesia',
		surface_area: '726.00',
		indep_year: '1979',
		population: '83000',
		life_expectancy: '59.8',
		gnp: '40.70',
		gnp_old: null,
		local_name: 'Kiribati',
		government_form: 'Republic',
		head_of_state: 'Teburoro Tito',
		capital: '2256',
		code_2: 'KI',
	},
	{
		code: 'KNA',
		name: 'Saint Kitts and Nevis',
		continent: Continent['North America'],
		region: 'Caribbean',
		surface_area: '261.00',
		indep_year: '1983',
		population: '38000',
		life_expectancy: '70.7',
		gnp: '299.00',
		gnp_old: null,
		local_name: 'Saint Kitts and Nevis',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Elisabeth II',
		capital: '3064',
		code_2: 'KN',
	},
	{
		code: 'KOR',
		name: 'South Korea',
		continent: Continent.Asia,
		region: 'Eastern Asia',
		surface_area: '99434.00',
		indep_year: '1948',
		population: '46844000',
		life_expectancy: '74.4',
		gnp: '320749.00',
		gnp_old: '442544.00',
		local_name: 'Taehan Min’guk (Namhan)',
		government_form: 'Republic',
		head_of_state: 'Kim Dae-jung',
		capital: '2331',
		code_2: 'KR',
	},
	{
		code: 'KWT',
		name: 'Kuwait',
		continent: Continent.Asia,
		region: 'Middle East',
		surface_area: '17818.00',
		indep_year: '1961',
		population: '1972000',
		life_expectancy: '76.1',
		gnp: '27037.00',
		gnp_old: '30373.00',
		local_name: 'Al-Kuwayt',
		government_form: 'Constitutional Monarchy (Emirate)',
		head_of_state: 'Jabir al-Ahmad al-Jabir al-Sabah',
		capital: '2429',
		code_2: 'KW',
	},
	{
		code: 'LAO',
		name: 'Laos',
		continent: Continent.Asia,
		region: 'Southeast Asia',
		surface_area: '236800.00',
		indep_year: '1953',
		population: '5433000',
		life_expectancy: '53.1',
		gnp: '1292.00',
		gnp_old: '1746.00',
		local_name: 'Lao',
		government_form: 'Republic',
		head_of_state: 'Khamtay Siphandone',
		capital: '2432',
		code_2: 'LA',
	},
	{
		code: 'LBN',
		name: 'Lebanon',
		continent: Continent.Asia,
		region: 'Middle East',
		surface_area: '10400.00',
		indep_year: '1941',
		population: '3282000',
		life_expectancy: '71.3',
		gnp: '17121.00',
		gnp_old: '15129.00',
		local_name: 'Lubnan',
		government_form: 'Republic',
		head_of_state: 'Émile Lahoud',
		capital: '2438',
		code_2: 'LB',
	},
	{
		code: 'LBR',
		name: 'Liberia',
		continent: Continent.Africa,
		region: 'Western Africa',
		surface_area: '111369.00',
		indep_year: '1847',
		population: '3154000',
		life_expectancy: '51.0',
		gnp: '2012.00',
		gnp_old: null,
		local_name: 'Liberia',
		government_form: 'Republic',
		head_of_state: 'Charles Taylor',
		capital: '2440',
		code_2: 'LR',
	},
	{
		code: 'LBY',
		name: 'Libyan Arab Jamahiriya',
		continent: Continent.Africa,
		region: 'Northern Africa',
		surface_area: '1759540.00',
		indep_year: '1951',
		population: '5605000',
		life_expectancy: '75.5',
		gnp: '44806.00',
		gnp_old: '40562.00',
		local_name: 'Libiya',
		government_form: 'Socialistic State',
		head_of_state: 'Muammar al-Qadhafi',
		capital: '2441',
		code_2: 'LY',
	},
	{
		code: 'LCA',
		name: 'Saint Lucia',
		continent: Continent['North America'],
		region: 'Caribbean',
		surface_area: '622.00',
		indep_year: '1979',
		population: '154000',
		life_expectancy: '72.3',
		gnp: '571.00',
		gnp_old: null,
		local_name: 'Saint Lucia',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Elisabeth II',
		capital: '3065',
		code_2: 'LC',
	},
	{
		code: 'LIE',
		name: 'Liechtenstein',
		continent: Continent.Europe,
		region: 'Western Europe',
		surface_area: '160.00',
		indep_year: '1806',
		population: '32300',
		life_expectancy: '78.8',
		gnp: '1119.00',
		gnp_old: '1084.00',
		local_name: 'Liechtenstein',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Hans-Adam II',
		capital: '2446',
		code_2: 'LI',
	},
	{
		code: 'LKA',
		name: 'Sri Lanka',
		continent: Continent.Asia,
		region: 'Southern and Central Asia',
		surface_area: '65610.00',
		indep_year: '1948',
		population: '18827000',
		life_expectancy: '71.8',
		gnp: '15706.00',
		gnp_old: '15091.00',
		local_name: 'Sri Lanka/Ilankai',
		government_form: 'Republic',
		head_of_state: 'Chandrika Kumaratunga',
		capital: '3217',
		code_2: 'LK',
	},
	{
		code: 'LSO',
		name: 'Lesotho',
		continent: Continent.Africa,
		region: 'Southern Africa',
		surface_area: '30355.00',
		indep_year: '1966',
		population: '2153000',
		life_expectancy: '50.8',
		gnp: '1061.00',
		gnp_old: '1161.00',
		local_name: 'Lesotho',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Letsie III',
		capital: '2437',
		code_2: 'LS',
	},
	{
		code: 'LTU',
		name: 'Lithuania',
		continent: Continent.Europe,
		region: 'Baltic Countries',
		surface_area: '65301.00',
		indep_year: '1991',
		population: '3698500',
		life_expectancy: '69.1',
		gnp: '10692.00',
		gnp_old: '9585.00',
		local_name: 'Lietuva',
		government_form: 'Republic',
		head_of_state: 'Valdas Adamkus',
		capital: '2447',
		code_2: 'LT',
	},
	{
		code: 'LUX',
		name: 'Luxembourg',
		continent: Continent.Europe,
		region: 'Western Europe',
		surface_area: '2586.00',
		indep_year: '1867',
		population: '435700',
		life_expectancy: '77.1',
		gnp: '16321.00',
		gnp_old: '15519.00',
		local_name: 'Luxembourg/Lëtzebuerg',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Henri',
		capital: '2452',
		code_2: 'LU',
	},
	{
		code: 'LVA',
		name: 'Latvia',
		continent: Continent.Europe,
		region: 'Baltic Countries',
		surface_area: '64589.00',
		indep_year: '1991',
		population: '2424200',
		life_expectancy: '68.4',
		gnp: '6398.00',
		gnp_old: '5639.00',
		local_name: 'Latvija',
		government_form: 'Republic',
		head_of_state: 'Vaira Vike-Freiberga',
		capital: '2434',
		code_2: 'LV',
	},
	{
		code: 'MAC',
		name: 'Macao',
		continent: Continent.Asia,
		region: 'Eastern Asia',
		surface_area: '18.00',
		indep_year: null,
		population: '473000',
		life_expectancy: '81.6',
		gnp: '5749.00',
		gnp_old: '5940.00',
		local_name: 'Macau/Aomen',
		government_form: 'Special Administrative Region of China',
		head_of_state: 'Jiang Zemin',
		capital: '2454',
		code_2: 'MO',
	},
	{
		code: 'MAR',
		name: 'Morocco',
		continent: Continent.Africa,
		region: 'Northern Africa',
		surface_area: '446550.00',
		indep_year: '1956',
		population: '28351000',
		life_expectancy: '69.1',
		gnp: '36124.00',
		gnp_old: '33514.00',
		local_name: 'Al-Maghrib',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Mohammed VI',
		capital: '2486',
		code_2: 'MA',
	},
	{
		code: 'MCO',
		name: 'Monaco',
		continent: Continent.Europe,
		region: 'Western Europe',
		surface_area: '1.50',
		indep_year: '1861',
		population: '34000',
		life_expectancy: '78.8',
		gnp: '776.00',
		gnp_old: null,
		local_name: 'Monaco',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Rainier III',
		capital: '2695',
		code_2: 'MC',
	},
	{
		code: 'MDA',
		name: 'Moldova',
		continent: Continent.Europe,
		region: 'Eastern Europe',
		surface_area: '33851.00',
		indep_year: '1991',
		population: '4380000',
		life_expectancy: '64.5',
		gnp: '1579.00',
		gnp_old: '1872.00',
		local_name: 'Moldova',
		government_form: 'Republic',
		head_of_state: 'Vladimir Voronin',
		capital: '2690',
		code_2: 'MD',
	},
	{
		code: 'MDG',
		name: 'Madagascar',
		continent: Continent.Africa,
		region: 'Eastern Africa',
		surface_area: '587041.00',
		indep_year: '1960',
		population: '15942000',
		life_expectancy: '55.0',
		gnp: '3750.00',
		gnp_old: '3545.00',
		local_name: 'Madagasikara/Madagascar',
		government_form: 'Federal Republic',
		head_of_state: 'Didier Ratsiraka',
		capital: '2455',
		code_2: 'MG',
	},
	{
		code: 'MDV',
		name: 'Maldives',
		continent: Continent.Asia,
		region: 'Southern and Central Asia',
		surface_area: '298.00',
		indep_year: '1965',
		population: '286000',
		life_expectancy: '62.2',
		gnp: '199.00',
		gnp_old: null,
		local_name: 'Dhivehi Raajje/Maldives',
		government_form: 'Republic',
		head_of_state: 'Maumoon Abdul Gayoom',
		capital: '2463',
		code_2: 'MV',
	},
	{
		code: 'MEX',
		name: 'Mexico',
		continent: Continent['North America'],
		region: 'Central America',
		surface_area: '1958201.00',
		indep_year: '1810',
		population: '98881000',
		life_expectancy: '71.5',
		gnp: '414972.00',
		gnp_old: '401461.00',
		local_name: 'México',
		government_form: 'Federal Republic',
		head_of_state: 'Vicente Fox Quesada',
		capital: '2515',
		code_2: 'MX',
	},
	{
		code: 'MHL',
		name: 'Marshall Islands',
		continent: Continent.Oceania,
		region: 'Micronesia',
		surface_area: '181.00',
		indep_year: '1990',
		population: '64000',
		life_expectancy: '65.5',
		gnp: '97.00',
		gnp_old: null,
		local_name: 'Marshall Islands/Majol',
		government_form: 'Republic',
		head_of_state: 'Kessai Note',
		capital: '2507',
		code_2: 'MH',
	},
	{
		code: 'MKD',
		name: 'Macedonia',
		continent: Continent.Europe,
		region: 'Southern Europe',
		surface_area: '25713.00',
		indep_year: '1991',
		population: '2024000',
		life_expectancy: '73.8',
		gnp: '1694.00',
		gnp_old: '1915.00',
		local_name: 'Makedonija',
		government_form: 'Republic',
		head_of_state: 'Boris Trajkovski',
		capital: '2460',
		code_2: 'MK',
	},
	{
		code: 'MLI',
		name: 'Mali',
		continent: Continent.Africa,
		region: 'Western Africa',
		surface_area: '1240192.00',
		indep_year: '1960',
		population: '11234000',
		life_expectancy: '46.7',
		gnp: '2642.00',
		gnp_old: '2453.00',
		local_name: 'Mali',
		government_form: 'Republic',
		head_of_state: 'Alpha Oumar Konaré',
		capital: '2482',
		code_2: 'ML',
	},
	{
		code: 'MLT',
		name: 'Malta',
		continent: Continent.Europe,
		region: 'Southern Europe',
		surface_area: '316.00',
		indep_year: '1964',
		population: '380200',
		life_expectancy: '77.9',
		gnp: '3512.00',
		gnp_old: '3338.00',
		local_name: 'Malta',
		government_form: 'Republic',
		head_of_state: 'Guido de Marco',
		capital: '2484',
		code_2: 'MT',
	},
	{
		code: 'MMR',
		name: 'Myanmar',
		continent: Continent.Asia,
		region: 'Southeast Asia',
		surface_area: '676578.00',
		indep_year: '1948',
		population: '45611000',
		life_expectancy: '54.9',
		gnp: '180375.00',
		gnp_old: '171028.00',
		local_name: 'Myanma Pye',
		government_form: 'Republic',
		head_of_state: 'kenraali Than Shwe',
		capital: '2710',
		code_2: 'MM',
	},
	{
		code: 'MNG',
		name: 'Mongolia',
		continent: Continent.Asia,
		region: 'Eastern Asia',
		surface_area: '1566500.00',
		indep_year: '1921',
		population: '2662000',
		life_expectancy: '67.3',
		gnp: '1043.00',
		gnp_old: '933.00',
		local_name: 'Mongol Uls',
		government_form: 'Republic',
		head_of_state: 'Natsagiin Bagabandi',
		capital: '2696',
		code_2: 'MN',
	},
	{
		code: 'MNP',
		name: 'Northern Mariana Islands',
		continent: Continent.Oceania,
		region: 'Micronesia',
		surface_area: '464.00',
		indep_year: null,
		population: '78000',
		life_expectancy: '75.5',
		gnp: '0.00',
		gnp_old: null,
		local_name: 'Northern Mariana Islands',
		government_form: 'Commonwealth of the US',
		head_of_state: 'George W. Bush',
		capital: '2913',
		code_2: 'MP',
	},
	{
		code: 'MOZ',
		name: 'Mozambique',
		continent: Continent.Africa,
		region: 'Eastern Africa',
		surface_area: '801590.00',
		indep_year: '1975',
		population: '19680000',
		life_expectancy: '37.5',
		gnp: '2891.00',
		gnp_old: '2711.00',
		local_name: 'Moçambique',
		government_form: 'Republic',
		head_of_state: 'Joaquím A. Chissano',
		capital: '2698',
		code_2: 'MZ',
	},
	{
		code: 'MRT',
		name: 'Mauritania',
		continent: Continent.Africa,
		region: 'Western Africa',
		surface_area: '1025520.00',
		indep_year: '1960',
		population: '2670000',
		life_expectancy: '50.8',
		gnp: '998.00',
		gnp_old: '1081.00',
		local_name: 'Muritaniya/Mauritanie',
		government_form: 'Republic',
		head_of_state: 'Maaouiya Ould Sid´Ahmad Taya',
		capital: '2509',
		code_2: 'MR',
	},
	{
		code: 'MSR',
		name: 'Montserrat',
		continent: Continent['North America'],
		region: 'Caribbean',
		surface_area: '102.00',
		indep_year: null,
		population: '11000',
		life_expectancy: '78.0',
		gnp: '109.00',
		gnp_old: null,
		local_name: 'Montserrat',
		government_form: 'Dependent Territory of the UK',
		head_of_state: 'Elisabeth II',
		capital: '2697',
		code_2: 'MS',
	},
	{
		code: 'MTQ',
		name: 'Martinique',
		continent: Continent['North America'],
		region: 'Caribbean',
		surface_area: '1102.00',
		indep_year: null,
		population: '395000',
		life_expectancy: '78.3',
		gnp: '2731.00',
		gnp_old: '2559.00',
		local_name: 'Martinique',
		government_form: 'Overseas Department of France',
		head_of_state: 'Jacques Chirac',
		capital: '2508',
		code_2: 'MQ',
	},
	{
		code: 'MUS',
		name: 'Mauritius',
		continent: Continent.Africa,
		region: 'Eastern Africa',
		surface_area: '2040.00',
		indep_year: '1968',
		population: '1158000',
		life_expectancy: '71.0',
		gnp: '4251.00',
		gnp_old: '4186.00',
		local_name: 'Mauritius',
		government_form: 'Republic',
		head_of_state: 'Cassam Uteem',
		capital: '2511',
		code_2: 'MU',
	},
	{
		code: 'MWI',
		name: 'Malawi',
		continent: Continent.Africa,
		region: 'Eastern Africa',
		surface_area: '118484.00',
		indep_year: '1964',
		population: '10925000',
		life_expectancy: '37.6',
		gnp: '1687.00',
		gnp_old: '2527.00',
		local_name: 'Malawi',
		government_form: 'Republic',
		head_of_state: 'Bakili Muluzi',
		capital: '2462',
		code_2: 'MW',
	},
	{
		code: 'MYS',
		name: 'Malaysia',
		continent: Continent.Asia,
		region: 'Southeast Asia',
		surface_area: '329758.00',
		indep_year: '1957',
		population: '22244000',
		life_expectancy: '70.8',
		gnp: '69213.00',
		gnp_old: '97884.00',
		local_name: 'Malaysia',
		government_form: 'Constitutional Monarchy, Federation',
		head_of_state: 'Salahuddin Abdul Aziz Shah Alhaj',
		capital: '2464',
		code_2: 'MY',
	},
	{
		code: 'MYT',
		name: 'Mayotte',
		continent: Continent.Africa,
		region: 'Eastern Africa',
		surface_area: '373.00',
		indep_year: null,
		population: '149000',
		life_expectancy: '59.5',
		gnp: '0.00',
		gnp_old: null,
		local_name: 'Mayotte',
		government_form: 'Territorial Collectivity of France',
		head_of_state: 'Jacques Chirac',
		capital: '2514',
		code_2: 'YT',
	},
	{
		code: 'NAM',
		name: 'Namibia',
		continent: Continent.Africa,
		region: 'Southern Africa',
		surface_area: '824292.00',
		indep_year: '1990',
		population: '1726000',
		life_expectancy: '42.5',
		gnp: '3101.00',
		gnp_old: '3384.00',
		local_name: 'Namibia',
		government_form: 'Republic',
		head_of_state: 'Sam Nujoma',
		capital: '2726',
		code_2: 'NA',
	},
	{
		code: 'NCL',
		name: 'New Caledonia',
		continent: Continent.Oceania,
		region: 'Melanesia',
		surface_area: '18575.00',
		indep_year: null,
		population: '214000',
		life_expectancy: '72.8',
		gnp: '3563.00',
		gnp_old: null,
		local_name: 'Nouvelle-Calédonie',
		government_form: 'Nonmetropolitan Territory of France',
		head_of_state: 'Jacques Chirac',
		capital: '3493',
		code_2: 'NC',
	},
	{
		code: 'NER',
		name: 'Niger',
		continent: Continent.Africa,
		region: 'Western Africa',
		surface_area: '1267000.00',
		indep_year: '1960',
		population: '10730000',
		life_expectancy: '41.3',
		gnp: '1706.00',
		gnp_old: '1580.00',
		local_name: 'Niger',
		government_form: 'Republic',
		head_of_state: 'Mamadou Tandja',
		capital: '2738',
		code_2: 'NE',
	},
	{
		code: 'NFK',
		name: 'Norfolk Island',
		continent: Continent.Oceania,
		region: 'Australia and New Zealand',
		surface_area: '36.00',
		indep_year: null,
		population: '2000',
		life_expectancy: null,
		gnp: '0.00',
		gnp_old: null,
		local_name: 'Norfolk Island',
		government_form: 'Territory of Australia',
		head_of_state: 'Elisabeth II',
		capital: '2806',
		code_2: 'NF',
	},
	{
		code: 'NGA',
		name: 'Nigeria',
		continent: Continent.Africa,
		region: 'Western Africa',
		surface_area: '923768.00',
		indep_year: '1960',
		population: '111506000',
		life_expectancy: '51.6',
		gnp: '65707.00',
		gnp_old: '58623.00',
		local_name: 'Nigeria',
		government_form: 'Federal Republic',
		head_of_state: 'Olusegun Obasanjo',
		capital: '2754',
		code_2: 'NG',
	},
	{
		code: 'NIC',
		name: 'Nicaragua',
		continent: Continent['North America'],
		region: 'Central America',
		surface_area: '130000.00',
		indep_year: '1838',
		population: '5074000',
		life_expectancy: '68.7',
		gnp: '1988.00',
		gnp_old: '2023.00',
		local_name: 'Nicaragua',
		government_form: 'Republic',
		head_of_state: 'Arnoldo Alemán Lacayo',
		capital: '2734',
		code_2: 'NI',
	},
	{
		code: 'NIU',
		name: 'Niue',
		continent: Continent.Oceania,
		region: 'Polynesia',
		surface_area: '260.00',
		indep_year: null,
		population: '2000',
		life_expectancy: null,
		gnp: '0.00',
		gnp_old: null,
		local_name: 'Niue',
		government_form: 'Nonmetropolitan Territory of New Zealand',
		head_of_state: 'Elisabeth II',
		capital: '2805',
		code_2: 'NU',
	},
	{
		code: 'NLD',
		name: 'Netherlands',
		continent: Continent.Europe,
		region: 'Western Europe',
		surface_area: '41526.00',
		indep_year: '1581',
		population: '15864000',
		life_expectancy: '78.3',
		gnp: '371362.00',
		gnp_old: '360478.00',
		local_name: 'Nederland',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Beatrix',
		capital: '5',
		code_2: 'NL',
	},
	{
		code: 'NOR',
		name: 'Norway',
		continent: Continent.Europe,
		region: 'Nordic Countries',
		surface_area: '323877.00',
		indep_year: '1905',
		population: '4478500',
		life_expectancy: '78.7',
		gnp: '145895.00',
		gnp_old: '153370.00',
		local_name: 'Norge',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Harald V',
		capital: '2807',
		code_2: 'NO',
	},
	{
		code: 'NPL',
		name: 'Nepal',
		continent: Continent.Asia,
		region: 'Southern and Central Asia',
		surface_area: '147181.00',
		indep_year: '1769',
		population: '23930000',
		life_expectancy: '57.8',
		gnp: '4768.00',
		gnp_old: '4837.00',
		local_name: 'Nepal',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Gyanendra Bir Bikram',
		capital: '2729',
		code_2: 'NP',
	},
	{
		code: 'NRU',
		name: 'Nauru',
		continent: Continent.Oceania,
		region: 'Micronesia',
		surface_area: '21.00',
		indep_year: '1968',
		population: '12000',
		life_expectancy: '60.8',
		gnp: '197.00',
		gnp_old: null,
		local_name: 'Naoero/Nauru',
		government_form: 'Republic',
		head_of_state: 'Bernard Dowiyogo',
		capital: '2728',
		code_2: 'NR',
	},
	{
		code: 'NZL',
		name: 'New Zealand',
		continent: Continent.Oceania,
		region: 'Australia and New Zealand',
		surface_area: '270534.00',
		indep_year: '1907',
		population: '3862000',
		life_expectancy: '77.8',
		gnp: '54669.00',
		gnp_old: '64960.00',
		local_name: 'New Zealand/Aotearoa',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Elisabeth II',
		capital: '3499',
		code_2: 'NZ',
	},
	{
		code: 'OMN',
		name: 'Oman',
		continent: Continent.Asia,
		region: 'Middle East',
		surface_area: '309500.00',
		indep_year: '1951',
		population: '2542000',
		life_expectancy: '71.8',
		gnp: '16904.00',
		gnp_old: '16153.00',
		local_name: '´Uman',
		government_form: 'Monarchy (Sultanate)',
		head_of_state: 'Qabus ibn Sa´id',
		capital: '2821',
		code_2: 'OM',
	},
	{
		code: 'PAK',
		name: 'Pakistan',
		continent: Continent.Asia,
		region: 'Southern and Central Asia',
		surface_area: '796095.00',
		indep_year: '1947',
		population: '156483000',
		life_expectancy: '61.1',
		gnp: '61289.00',
		gnp_old: '58549.00',
		local_name: 'Pakistan',
		government_form: 'Republic',
		head_of_state: 'Mohammad Rafiq Tarar',
		capital: '2831',
		code_2: 'PK',
	},
	{
		code: 'PAN',
		name: 'Panama',
		continent: Continent['North America'],
		region: 'Central America',
		surface_area: '75517.00',
		indep_year: '1903',
		population: '2856000',
		life_expectancy: '75.5',
		gnp: '9131.00',
		gnp_old: '8700.00',
		local_name: 'Panamá',
		government_form: 'Republic',
		head_of_state: 'Mireya Elisa Moscoso Rodríguez',
		capital: '2882',
		code_2: 'PA',
	},
	{
		code: 'PCN',
		name: 'Pitcairn',
		continent: Continent.Oceania,
		region: 'Polynesia',
		surface_area: '49.00',
		indep_year: null,
		population: '50',
		life_expectancy: null,
		gnp: '0.00',
		gnp_old: null,
		local_name: 'Pitcairn',
		government_form: 'Dependent Territory of the UK',
		head_of_state: 'Elisabeth II',
		capital: '2912',
		code_2: 'PN',
	},
	{
		code: 'PER',
		name: 'Peru',
		continent: Continent['South America'],
		region: 'South America',
		surface_area: '1285216.00',
		indep_year: '1821',
		population: '25662000',
		life_expectancy: '70.0',
		gnp: '64140.00',
		gnp_old: '65186.00',
		local_name: 'Perú/Piruw',
		government_form: 'Republic',
		head_of_state: 'Valentin Paniagua Corazao',
		capital: '2890',
		code_2: 'PE',
	},
	{
		code: 'PHL',
		name: 'Philippines',
		continent: Continent.Asia,
		region: 'Southeast Asia',
		surface_area: '300000.00',
		indep_year: '1946',
		population: '75967000',
		life_expectancy: '67.5',
		gnp: '65107.00',
		gnp_old: '82239.00',
		local_name: 'Pilipinas',
		government_form: 'Republic',
		head_of_state: 'Gloria Macapagal-Arroyo',
		capital: '766',
		code_2: 'PH',
	},
	{
		code: 'PLW',
		name: 'Palau',
		continent: Continent.Oceania,
		region: 'Micronesia',
		surface_area: '459.00',
		indep_year: '1994',
		population: '19000',
		life_expectancy: '68.6',
		gnp: '105.00',
		gnp_old: null,
		local_name: 'Belau/Palau',
		government_form: 'Republic',
		head_of_state: 'Kuniwo Nakamura',
		capital: '2881',
		code_2: 'PW',
	},
	{
		code: 'PNG',
		name: 'Papua New Guinea',
		continent: Continent.Oceania,
		region: 'Melanesia',
		surface_area: '462840.00',
		indep_year: '1975',
		population: '4807000',
		life_expectancy: '63.1',
		gnp: '4988.00',
		gnp_old: '6328.00',
		local_name: 'Papua New Guinea/Papua Niugini',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Elisabeth II',
		capital: '2884',
		code_2: 'PG',
	},
	{
		code: 'POL',
		name: 'Poland',
		continent: Continent.Europe,
		region: 'Eastern Europe',
		surface_area: '323250.00',
		indep_year: '1918',
		population: '38653600',
		life_expectancy: '73.2',
		gnp: '151697.00',
		gnp_old: '135636.00',
		local_name: 'Polska',
		government_form: 'Republic',
		head_of_state: 'Aleksander Kwasniewski',
		capital: '2928',
		code_2: 'PL',
	},
	{
		code: 'PRI',
		name: 'Puerto Rico',
		continent: Continent['North America'],
		region: 'Caribbean',
		surface_area: '8875.00',
		indep_year: null,
		population: '3869000',
		life_expectancy: '75.6',
		gnp: '34100.00',
		gnp_old: '32100.00',
		local_name: 'Puerto Rico',
		government_form: 'Commonwealth of the US',
		head_of_state: 'George W. Bush',
		capital: '2919',
		code_2: 'PR',
	},
	{
		code: 'PRK',
		name: 'North Korea',
		continent: Continent.Asia,
		region: 'Eastern Asia',
		surface_area: '120538.00',
		indep_year: '1948',
		population: '24039000',
		life_expectancy: '70.7',
		gnp: '5332.00',
		gnp_old: null,
		local_name: 'Choson Minjujuui In´min Konghwaguk (Bukhan)',
		government_form: 'Socialistic Republic',
		head_of_state: 'Kim Jong-il',
		capital: '2318',
		code_2: 'KP',
	},
	{
		code: 'PRT',
		name: 'Portugal',
		continent: Continent.Europe,
		region: 'Southern Europe',
		surface_area: '91982.00',
		indep_year: '1143',
		population: '9997600',
		life_expectancy: '75.8',
		gnp: '105954.00',
		gnp_old: '102133.00',
		local_name: 'Portugal',
		government_form: 'Republic',
		head_of_state: 'Jorge Sampãio',
		capital: '2914',
		code_2: 'PT',
	},
	{
		code: 'PRY',
		name: 'Paraguay',
		continent: Continent['South America'],
		region: 'South America',
		surface_area: '406752.00',
		indep_year: '1811',
		population: '5496000',
		life_expectancy: '73.7',
		gnp: '8444.00',
		gnp_old: '9555.00',
		local_name: 'Paraguay',
		government_form: 'Republic',
		head_of_state: 'Luis Ángel González Macchi',
		capital: '2885',
		code_2: 'PY',
	},
	{
		code: 'PSE',
		name: 'Palestine',
		continent: Continent.Asia,
		region: 'Middle East',
		surface_area: '6257.00',
		indep_year: null,
		population: '3101000',
		life_expectancy: '71.4',
		gnp: '4173.00',
		gnp_old: null,
		local_name: 'Filastin',
		government_form: 'Autonomous Area',
		head_of_state: 'Yasser (Yasir) Arafat',
		capital: '4074',
		code_2: 'PS',
	},
	{
		code: 'PYF',
		name: 'French Polynesia',
		continent: Continent.Oceania,
		region: 'Polynesia',
		surface_area: '4000.00',
		indep_year: null,
		population: '235000',
		life_expectancy: '74.8',
		gnp: '818.00',
		gnp_old: '781.00',
		local_name: 'Polynésie française',
		government_form: 'Nonmetropolitan Territory of France',
		head_of_state: 'Jacques Chirac',
		capital: '3016',
		code_2: 'PF',
	},
	{
		code: 'QAT',
		name: 'Qatar',
		continent: Continent.Asia,
		region: 'Middle East',
		surface_area: '11000.00',
		indep_year: '1971',
		population: '599000',
		life_expectancy: '72.4',
		gnp: '9472.00',
		gnp_old: '8920.00',
		local_name: 'Qatar',
		government_form: 'Monarchy',
		head_of_state: 'Hamad ibn Khalifa al-Thani',
		capital: '2973',
		code_2: 'QA',
	},
	{
		code: 'REU',
		name: 'Réunion',
		continent: Continent.Africa,
		region: 'Eastern Africa',
		surface_area: '2510.00',
		indep_year: null,
		population: '699000',
		life_expectancy: '72.7',
		gnp: '8287.00',
		gnp_old: '7988.00',
		local_name: 'Réunion',
		government_form: 'Overseas Department of France',
		head_of_state: 'Jacques Chirac',
		capital: '3017',
		code_2: 'RE',
	},
	{
		code: 'ROM',
		name: 'Romania',
		continent: Continent.Europe,
		region: 'Eastern Europe',
		surface_area: '238391.00',
		indep_year: '1878',
		population: '22455500',
		life_expectancy: '69.9',
		gnp: '38158.00',
		gnp_old: '34843.00',
		local_name: 'România',
		government_form: 'Republic',
		head_of_state: 'Ion Iliescu',
		capital: '3018',
		code_2: 'RO',
	},
	{
		code: 'RUS',
		name: 'Russian Federation',
		continent: Continent.Europe,
		region: 'Eastern Europe',
		surface_area: '17075400.00',
		indep_year: '1991',
		population: '146934000',
		life_expectancy: '67.2',
		gnp: '276608.00',
		gnp_old: '442989.00',
		local_name: 'Rossija',
		government_form: 'Federal Republic',
		head_of_state: 'Vladimir Putin',
		capital: '3580',
		code_2: 'RU',
	},
	{
		code: 'RWA',
		name: 'Rwanda',
		continent: Continent.Africa,
		region: 'Eastern Africa',
		surface_area: '26338.00',
		indep_year: '1962',
		population: '7733000',
		life_expectancy: '39.3',
		gnp: '2036.00',
		gnp_old: '1863.00',
		local_name: 'Rwanda/Urwanda',
		government_form: 'Republic',
		head_of_state: 'Paul Kagame',
		capital: '3047',
		code_2: 'RW',
	},
	{
		code: 'SAU',
		name: 'Saudi Arabia',
		continent: Continent.Asia,
		region: 'Middle East',
		surface_area: '2149690.00',
		indep_year: '1932',
		population: '21607000',
		life_expectancy: '67.8',
		gnp: '137635.00',
		gnp_old: '146171.00',
		local_name: 'Al-´Arabiya as-Sa´udiya',
		government_form: 'Monarchy',
		head_of_state: 'Fahd ibn Abdul-Aziz al-Sa´ud',
		capital: '3173',
		code_2: 'SA',
	},
	{
		code: 'SDN',
		name: 'Sudan',
		continent: Continent.Africa,
		region: 'Northern Africa',
		surface_area: '2505813.00',
		indep_year: '1956',
		population: '29490000',
		life_expectancy: '56.6',
		gnp: '10162.00',
		gnp_old: null,
		local_name: 'As-Sudan',
		government_form: 'Islamic Republic',
		head_of_state: 'Omar Hassan Ahmad al-Bashir',
		capital: '3225',
		code_2: 'SD',
	},
	{
		code: 'SEN',
		name: 'Senegal',
		continent: Continent.Africa,
		region: 'Western Africa',
		surface_area: '196722.00',
		indep_year: '1960',
		population: '9481000',
		life_expectancy: '62.2',
		gnp: '4787.00',
		gnp_old: '4542.00',
		local_name: 'Sénégal/Sounougal',
		government_form: 'Republic',
		head_of_state: 'Abdoulaye Wade',
		capital: '3198',
		code_2: 'SN',
	},
	{
		code: 'SGP',
		name: 'Singapore',
		continent: Continent.Asia,
		region: 'Southeast Asia',
		surface_area: '618.00',
		indep_year: '1965',
		population: '3567000',
		life_expectancy: '80.1',
		gnp: '86503.00',
		gnp_old: '96318.00',
		local_name: 'Singapore/Singapura/Xinjiapo/Singapur',
		government_form: 'Republic',
		head_of_state: 'Sellapan Rama Nathan',
		capital: '3208',
		code_2: 'SG',
	},
	{
		code: 'SGS',
		name: 'South Georgia and the South Sandwich Islands',
		continent: Continent.Antarctica,
		region: 'Antarctica',
		surface_area: '3903.00',
		indep_year: null,
		population: '0',
		life_expectancy: null,
		gnp: '0.00',
		gnp_old: null,
		local_name: 'South Georgia and the South Sandwich Islands',
		government_form: 'Dependent Territory of the UK',
		head_of_state: 'Elisabeth II',
		capital: null,
		code_2: 'GS',
	},
	{
		code: 'SHN',
		name: 'Saint Helena',
		continent: Continent.Africa,
		region: 'Western Africa',
		surface_area: '314.00',
		indep_year: null,
		population: '6000',
		life_expectancy: '76.8',
		gnp: '0.00',
		gnp_old: null,
		local_name: 'Saint Helena',
		government_form: 'Dependent Territory of the UK',
		head_of_state: 'Elisabeth II',
		capital: '3063',
		code_2: 'SH',
	},
	{
		code: 'SJM',
		name: 'Svalbard and Jan Mayen',
		continent: Continent.Europe,
		region: 'Nordic Countries',
		surface_area: '62422.00',
		indep_year: null,
		population: '3200',
		life_expectancy: null,
		gnp: '0.00',
		gnp_old: null,
		local_name: 'Svalbard og Jan Mayen',
		government_form: 'Dependent Territory of Norway',
		head_of_state: 'Harald V',
		capital: '938',
		code_2: 'SJ',
	},
	{
		code: 'SLB',
		name: 'Solomon Islands',
		continent: Continent.Oceania,
		region: 'Melanesia',
		surface_area: '28896.00',
		indep_year: '1978',
		population: '444000',
		life_expectancy: '71.3',
		gnp: '182.00',
		gnp_old: '220.00',
		local_name: 'Solomon Islands',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Elisabeth II',
		capital: '3161',
		code_2: 'SB',
	},
	{
		code: 'SLE',
		name: 'Sierra Leone',
		continent: Continent.Africa,
		region: 'Western Africa',
		surface_area: '71740.00',
		indep_year: '1961',
		population: '4854000',
		life_expectancy: '45.3',
		gnp: '746.00',
		gnp_old: '858.00',
		local_name: 'Sierra Leone',
		government_form: 'Republic',
		head_of_state: 'Ahmed Tejan Kabbah',
		capital: '3207',
		code_2: 'SL',
	},
	{
		code: 'SLV',
		name: 'El Salvador',
		continent: Continent['North America'],
		region: 'Central America',
		surface_area: '21041.00',
		indep_year: '1841',
		population: '6276000',
		life_expectancy: '69.7',
		gnp: '11863.00',
		gnp_old: '11203.00',
		local_name: 'El Salvador',
		government_form: 'Republic',
		head_of_state: 'Francisco Guillermo Flores Pérez',
		capital: '645',
		code_2: 'SV',
	},
	{
		code: 'SMR',
		name: 'San Marino',
		continent: Continent.Europe,
		region: 'Southern Europe',
		surface_area: '61.00',
		indep_year: '885',
		population: '27000',
		life_expectancy: '81.1',
		gnp: '510.00',
		gnp_old: null,
		local_name: 'San Marino',
		government_form: 'Republic',
		head_of_state: null,
		capital: '3171',
		code_2: 'SM',
	},
	{
		code: 'SOM',
		name: 'Somalia',
		continent: Continent.Africa,
		region: 'Eastern Africa',
		surface_area: '637657.00',
		indep_year: '1960',
		population: '10097000',
		life_expectancy: '46.2',
		gnp: '935.00',
		gnp_old: null,
		local_name: 'Soomaaliya',
		government_form: 'Republic',
		head_of_state: 'Abdiqassim Salad Hassan',
		capital: '3214',
		code_2: 'SO',
	},
	{
		code: 'SPM',
		name: 'Saint Pierre and Miquelon',
		continent: Continent['North America'],
		region: 'North America',
		surface_area: '242.00',
		indep_year: null,
		population: '7000',
		life_expectancy: '77.6',
		gnp: '0.00',
		gnp_old: null,
		local_name: 'Saint-Pierre-et-Miquelon',
		government_form: 'Territorial Collectivity of France',
		head_of_state: 'Jacques Chirac',
		capital: '3067',
		code_2: 'PM',
	},
	{
		code: 'STP',
		name: 'Sao Tome and Principe',
		continent: Continent.Africa,
		region: 'Central Africa',
		surface_area: '964.00',
		indep_year: '1975',
		population: '147000',
		life_expectancy: '65.3',
		gnp: '6.00',
		gnp_old: null,
		local_name: 'São Tomé e Príncipe',
		government_form: 'Republic',
		head_of_state: 'Miguel Trovoada',
		capital: '3172',
		code_2: 'ST',
	},
	{
		code: 'SUR',
		name: 'Suriname',
		continent: Continent['South America'],
		region: 'South America',
		surface_area: '163265.00',
		indep_year: '1975',
		population: '417000',
		life_expectancy: '71.4',
		gnp: '870.00',
		gnp_old: '706.00',
		local_name: 'Suriname',
		government_form: 'Republic',
		head_of_state: 'Ronald Venetiaan',
		capital: '3243',
		code_2: 'SR',
	},
	{
		code: 'SVK',
		name: 'Slovakia',
		continent: Continent.Europe,
		region: 'Eastern Europe',
		surface_area: '49012.00',
		indep_year: '1993',
		population: '5398700',
		life_expectancy: '73.7',
		gnp: '20594.00',
		gnp_old: '19452.00',
		local_name: 'Slovensko',
		government_form: 'Republic',
		head_of_state: 'Rudolf Schuster',
		capital: '3209',
		code_2: 'SK',
	},
	{
		code: 'SVN',
		name: 'Slovenia',
		continent: Continent.Europe,
		region: 'Southern Europe',
		surface_area: '20256.00',
		indep_year: '1991',
		population: '1987800',
		life_expectancy: '74.9',
		gnp: '19756.00',
		gnp_old: '18202.00',
		local_name: 'Slovenija',
		government_form: 'Republic',
		head_of_state: 'Milan Kucan',
		capital: '3212',
		code_2: 'SI',
	},
	{
		code: 'SWE',
		name: 'Sweden',
		continent: Continent.Europe,
		region: 'Nordic Countries',
		surface_area: '449964.00',
		indep_year: '836',
		population: '8861400',
		life_expectancy: '79.6',
		gnp: '226492.00',
		gnp_old: '227757.00',
		local_name: 'Sverige',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Carl XVI Gustaf',
		capital: '3048',
		code_2: 'SE',
	},
	{
		code: 'SWZ',
		name: 'Swaziland',
		continent: Continent.Africa,
		region: 'Southern Africa',
		surface_area: '17364.00',
		indep_year: '1968',
		population: '1008000',
		life_expectancy: '40.4',
		gnp: '1206.00',
		gnp_old: '1312.00',
		local_name: 'kaNgwane',
		government_form: 'Monarchy',
		head_of_state: 'Mswati III',
		capital: '3244',
		code_2: 'SZ',
	},
	{
		code: 'SYC',
		name: 'Seychelles',
		continent: Continent.Africa,
		region: 'Eastern Africa',
		surface_area: '455.00',
		indep_year: '1976',
		population: '77000',
		life_expectancy: '70.4',
		gnp: '536.00',
		gnp_old: '539.00',
		local_name: 'Sesel/Seychelles',
		government_form: 'Republic',
		head_of_state: 'France-Albert René',
		capital: '3206',
		code_2: 'SC',
	},
	{
		code: 'SYR',
		name: 'Syria',
		continent: Continent.Asia,
		region: 'Middle East',
		surface_area: '185180.00',
		indep_year: '1941',
		population: '16125000',
		life_expectancy: '68.5',
		gnp: '65984.00',
		gnp_old: '64926.00',
		local_name: 'Suriya',
		government_form: 'Republic',
		head_of_state: 'Bashar al-Assad',
		capital: '3250',
		code_2: 'SY',
	},
	{
		code: 'TCA',
		name: 'Turks and Caicos Islands',
		continent: Continent['North America'],
		region: 'Caribbean',
		surface_area: '430.00',
		indep_year: null,
		population: '17000',
		life_expectancy: '73.3',
		gnp: '96.00',
		gnp_old: null,
		local_name: 'The Turks and Caicos Islands',
		government_form: 'Dependent Territory of the UK',
		head_of_state: 'Elisabeth II',
		capital: '3423',
		code_2: 'TC',
	},
	{
		code: 'TCD',
		name: 'Chad',
		continent: Continent.Africa,
		region: 'Central Africa',
		surface_area: '1284000.00',
		indep_year: '1960',
		population: '7651000',
		life_expectancy: '50.5',
		gnp: '1208.00',
		gnp_old: '1102.00',
		local_name: 'Tchad/Tshad',
		government_form: 'Republic',
		head_of_state: 'Idriss Déby',
		capital: '3337',
		code_2: 'TD',
	},
	{
		code: 'TGO',
		name: 'Togo',
		continent: Continent.Africa,
		region: 'Western Africa',
		surface_area: '56785.00',
		indep_year: '1960',
		population: '4629000',
		life_expectancy: '54.7',
		gnp: '1449.00',
		gnp_old: '1400.00',
		local_name: 'Togo',
		government_form: 'Republic',
		head_of_state: 'Gnassingbé Eyadéma',
		capital: '3332',
		code_2: 'TG',
	},
	{
		code: 'THA',
		name: 'Thailand',
		continent: Continent.Asia,
		region: 'Southeast Asia',
		surface_area: '513115.00',
		indep_year: '1350',
		population: '61399000',
		life_expectancy: '68.6',
		gnp: '116416.00',
		gnp_old: '153907.00',
		local_name: 'Prathet Thai',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Bhumibol Adulyadej',
		capital: '3320',
		code_2: 'TH',
	},
	{
		code: 'TJK',
		name: 'Tajikistan',
		continent: Continent.Asia,
		region: 'Southern and Central Asia',
		surface_area: '143100.00',
		indep_year: '1991',
		population: '6188000',
		life_expectancy: '64.1',
		gnp: '1990.00',
		gnp_old: '1056.00',
		local_name: 'Toçikiston',
		government_form: 'Republic',
		head_of_state: 'Emomali Rahmonov',
		capital: '3261',
		code_2: 'TJ',
	},
	{
		code: 'TKL',
		name: 'Tokelau',
		continent: Continent.Oceania,
		region: 'Polynesia',
		surface_area: '12.00',
		indep_year: null,
		population: '2000',
		life_expectancy: null,
		gnp: '0.00',
		gnp_old: null,
		local_name: 'Tokelau',
		government_form: 'Nonmetropolitan Territory of New Zealand',
		head_of_state: 'Elisabeth II',
		capital: '3333',
		code_2: 'TK',
	},
	{
		code: 'TKM',
		name: 'Turkmenistan',
		continent: Continent.Asia,
		region: 'Southern and Central Asia',
		surface_area: '488100.00',
		indep_year: '1991',
		population: '4459000',
		life_expectancy: '60.9',
		gnp: '4397.00',
		gnp_old: '2000.00',
		local_name: 'Türkmenostan',
		government_form: 'Republic',
		head_of_state: 'Saparmurad Nijazov',
		capital: '3419',
		code_2: 'TM',
	},
	{
		code: 'TMP',
		name: 'East Timor',
		continent: Continent.Asia,
		region: 'Southeast Asia',
		surface_area: '14874.00',
		indep_year: null,
		population: '885000',
		life_expectancy: '46.0',
		gnp: '0.00',
		gnp_old: null,
		local_name: 'Timor Timur',
		government_form: 'Administrated by the UN',
		head_of_state: 'José Alexandre Gusmão',
		capital: '1522',
		code_2: 'TP',
	},
	{
		code: 'TON',
		name: 'Tonga',
		continent: Continent.Oceania,
		region: 'Polynesia',
		surface_area: '650.00',
		indep_year: '1970',
		population: '99000',
		life_expectancy: '67.9',
		gnp: '146.00',
		gnp_old: '170.00',
		local_name: 'Tonga',
		government_form: 'Monarchy',
		head_of_state: "Taufa'ahau Tupou IV",
		capital: '3334',
		code_2: 'TO',
	},
	{
		code: 'TTO',
		name: 'Trinidad and Tobago',
		continent: Continent['North America'],
		region: 'Caribbean',
		surface_area: '5130.00',
		indep_year: '1962',
		population: '1295000',
		life_expectancy: '68.0',
		gnp: '6232.00',
		gnp_old: '5867.00',
		local_name: 'Trinidad and Tobago',
		government_form: 'Republic',
		head_of_state: 'Arthur N. R. Robinson',
		capital: '3336',
		code_2: 'TT',
	},
	{
		code: 'TUN',
		name: 'Tunisia',
		continent: Continent.Africa,
		region: 'Northern Africa',
		surface_area: '163610.00',
		indep_year: '1956',
		population: '9586000',
		life_expectancy: '73.7',
		gnp: '20026.00',
		gnp_old: '18898.00',
		local_name: 'Tunis/Tunisie',
		government_form: 'Republic',
		head_of_state: 'Zine al-Abidine Ben Ali',
		capital: '3349',
		code_2: 'TN',
	},
	{
		code: 'TUR',
		name: 'Turkey',
		continent: Continent.Asia,
		region: 'Middle East',
		surface_area: '774815.00',
		indep_year: '1923',
		population: '66591000',
		life_expectancy: '71.0',
		gnp: '210721.00',
		gnp_old: '189122.00',
		local_name: 'Türkiye',
		government_form: 'Republic',
		head_of_state: 'Ahmet Necdet Sezer',
		capital: '3358',
		code_2: 'TR',
	},
	{
		code: 'TUV',
		name: 'Tuvalu',
		continent: Continent.Oceania,
		region: 'Polynesia',
		surface_area: '26.00',
		indep_year: '1978',
		population: '12000',
		life_expectancy: '66.3',
		gnp: '6.00',
		gnp_old: null,
		local_name: 'Tuvalu',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Elisabeth II',
		capital: '3424',
		code_2: 'TV',
	},
	{
		code: 'TWN',
		name: 'Taiwan',
		continent: Continent.Asia,
		region: 'Eastern Asia',
		surface_area: '36188.00',
		indep_year: '1945',
		population: '22256000',
		life_expectancy: '76.4',
		gnp: '256254.00',
		gnp_old: '263451.00',
		local_name: 'T’ai-wan',
		government_form: 'Republic',
		head_of_state: 'Chen Shui-bian',
		capital: '3263',
		code_2: 'TW',
	},
	{
		code: 'TZA',
		name: 'Tanzania',
		continent: Continent.Africa,
		region: 'Eastern Africa',
		surface_area: '883749.00',
		indep_year: '1961',
		population: '33517000',
		life_expectancy: '52.3',
		gnp: '8005.00',
		gnp_old: '7388.00',
		local_name: 'Tanzania',
		government_form: 'Republic',
		head_of_state: 'Benjamin William Mkapa',
		capital: '3306',
		code_2: 'TZ',
	},
	{
		code: 'UGA',
		name: 'Uganda',
		continent: Continent.Africa,
		region: 'Eastern Africa',
		surface_area: '241038.00',
		indep_year: '1962',
		population: '21778000',
		life_expectancy: '42.9',
		gnp: '6313.00',
		gnp_old: '6887.00',
		local_name: 'Uganda',
		government_form: 'Republic',
		head_of_state: 'Yoweri Museveni',
		capital: '3425',
		code_2: 'UG',
	},
	{
		code: 'UKR',
		name: 'Ukraine',
		continent: Continent.Europe,
		region: 'Eastern Europe',
		surface_area: '603700.00',
		indep_year: '1991',
		population: '50456000',
		life_expectancy: '66.0',
		gnp: '42168.00',
		gnp_old: '49677.00',
		local_name: 'Ukrajina',
		government_form: 'Republic',
		head_of_state: 'Leonid Kutšma',
		capital: '3426',
		code_2: 'UA',
	},
	{
		code: 'UMI',
		name: 'United States Minor Outlying Islands',
		continent: Continent.Oceania,
		region: 'Micronesia/Caribbean',
		surface_area: '16.00',
		indep_year: null,
		population: '0',
		life_expectancy: null,
		gnp: '0.00',
		gnp_old: null,
		local_name: 'United States Minor Outlying Islands',
		government_form: 'Dependent Territory of the US',
		head_of_state: 'George W. Bush',
		capital: null,
		code_2: 'UM',
	},
	{
		code: 'URY',
		name: 'Uruguay',
		continent: Continent['South America'],
		region: 'South America',
		surface_area: '175016.00',
		indep_year: '1828',
		population: '3337000',
		life_expectancy: '75.2',
		gnp: '20831.00',
		gnp_old: '19967.00',
		local_name: 'Uruguay',
		government_form: 'Republic',
		head_of_state: 'Jorge Batlle Ibáñez',
		capital: '3492',
		code_2: 'UY',
	},
	{
		code: 'USA',
		name: 'United States',
		continent: Continent['North America'],
		region: 'North America',
		surface_area: '9363520.00',
		indep_year: '1776',
		population: '278357000',
		life_expectancy: '77.1',
		gnp: '8510700.00',
		gnp_old: '8110900.00',
		local_name: 'United States',
		government_form: 'Federal Republic',
		head_of_state: 'George W. Bush',
		capital: '3813',
		code_2: 'US',
	},
	{
		code: 'UZB',
		name: 'Uzbekistan',
		continent: Continent.Asia,
		region: 'Southern and Central Asia',
		surface_area: '447400.00',
		indep_year: '1991',
		population: '24318000',
		life_expectancy: '63.7',
		gnp: '14194.00',
		gnp_old: '21300.00',
		local_name: 'Uzbekiston',
		government_form: 'Republic',
		head_of_state: 'Islam Karimov',
		capital: '3503',
		code_2: 'UZ',
	},
	{
		code: 'VAT',
		name: 'Holy See (Vatican City State)',
		continent: Continent.Europe,
		region: 'Southern Europe',
		surface_area: '0.40',
		indep_year: '1929',
		population: '1000',
		life_expectancy: null,
		gnp: '9.00',
		gnp_old: null,
		local_name: 'Santa Sede/Città del Vaticano',
		government_form: 'Independent Church State',
		head_of_state: 'Johannes Paavali II',
		capital: '3538',
		code_2: 'VA',
	},
	{
		code: 'VCT',
		name: 'Saint Vincent and the Grenadines',
		continent: Continent['North America'],
		region: 'Caribbean',
		surface_area: '388.00',
		indep_year: '1979',
		population: '114000',
		life_expectancy: '72.3',
		gnp: '285.00',
		gnp_old: null,
		local_name: 'Saint Vincent and the Grenadines',
		government_form: 'Constitutional Monarchy',
		head_of_state: 'Elisabeth II',
		capital: '3066',
		code_2: 'VC',
	},
	{
		code: 'VEN',
		name: 'Venezuela',
		continent: Continent['South America'],
		region: 'South America',
		surface_area: '912050.00',
		indep_year: '1811',
		population: '24170000',
		life_expectancy: '73.1',
		gnp: '95023.00',
		gnp_old: '88434.00',
		local_name: 'Venezuela',
		government_form: 'Federal Republic',
		head_of_state: 'Hugo Chávez Frías',
		capital: '3539',
		code_2: 'VE',
	},
	{
		code: 'VGB',
		name: 'Virgin Islands, British',
		continent: Continent['North America'],
		region: 'Caribbean',
		surface_area: '151.00',
		indep_year: null,
		population: '21000',
		life_expectancy: '75.4',
		gnp: '612.00',
		gnp_old: '573.00',
		local_name: 'British Virgin Islands',
		government_form: 'Dependent Territory of the UK',
		head_of_state: 'Elisabeth II',
		capital: '537',
		code_2: 'VG',
	},
	{
		code: 'VIR',
		name: 'Virgin Islands, U.S.',
		continent: Continent['North America'],
		region: 'Caribbean',
		surface_area: '347.00',
		indep_year: null,
		population: '93000',
		life_expectancy: '78.1',
		gnp: '0.00',
		gnp_old: null,
		local_name: 'Virgin Islands of the United States',
		government_form: 'US Territory',
		head_of_state: 'George W. Bush',
		capital: '4067',
		code_2: 'VI',
	},
	{
		code: 'VNM',
		name: 'Vietnam',
		continent: Continent.Asia,
		region: 'Southeast Asia',
		surface_area: '331689.00',
		indep_year: '1945',
		population: '79832000',
		life_expectancy: '69.3',
		gnp: '21929.00',
		gnp_old: '22834.00',
		local_name: 'Viêt Nam',
		government_form: 'Socialistic Republic',
		head_of_state: 'Trân Duc Luong',
		capital: '3770',
		code_2: 'VN',
	},
	{
		code: 'VUT',
		name: 'Vanuatu',
		continent: Continent.Oceania,
		region: 'Melanesia',
		surface_area: '12189.00',
		indep_year: '1980',
		population: '190000',
		life_expectancy: '60.6',
		gnp: '261.00',
		gnp_old: '246.00',
		local_name: 'Vanuatu',
		government_form: 'Republic',
		head_of_state: 'John Bani',
		capital: '3537',
		code_2: 'VU',
	},
	{
		code: 'WLF',
		name: 'Wallis and Futuna',
		continent: Continent.Oceania,
		region: 'Polynesia',
		surface_area: '200.00',
		indep_year: null,
		population: '15000',
		life_expectancy: null,
		gnp: '0.00',
		gnp_old: null,
		local_name: 'Wallis-et-Futuna',
		government_form: 'Nonmetropolitan Territory of France',
		head_of_state: 'Jacques Chirac',
		capital: '3536',
		code_2: 'WF',
	},
	{
		code: 'WSM',
		name: 'Samoa',
		continent: Continent.Oceania,
		region: 'Polynesia',
		surface_area: '2831.00',
		indep_year: '1962',
		population: '180000',
		life_expectancy: '69.2',
		gnp: '141.00',
		gnp_old: '157.00',
		local_name: 'Samoa',
		government_form: 'Parlementary Monarchy',
		head_of_state: 'Malietoa Tanumafili II',
		capital: '3169',
		code_2: 'WS',
	},
	{
		code: 'YEM',
		name: 'Yemen',
		continent: Continent.Asia,
		region: 'Middle East',
		surface_area: '527968.00',
		indep_year: '1918',
		population: '18112000',
		life_expectancy: '59.8',
		gnp: '6041.00',
		gnp_old: '5729.00',
		local_name: 'Al-Yaman',
		government_form: 'Republic',
		head_of_state: 'Ali Abdallah Salih',
		capital: '1780',
		code_2: 'YE',
	},
	{
		code: 'YUG',
		name: 'Yugoslavia',
		continent: Continent.Europe,
		region: 'Southern Europe',
		surface_area: '102173.00',
		indep_year: '1918',
		population: '10640000',
		life_expectancy: '72.4',
		gnp: '17000.00',
		gnp_old: null,
		local_name: 'Jugoslavija',
		government_form: 'Federal Republic',
		head_of_state: 'Vojislav Koštunica',
		capital: '1792',
		code_2: 'YU',
	},
	{
		code: 'ZAF',
		name: 'South Africa',
		continent: Continent.Africa,
		region: 'Southern Africa',
		surface_area: '1221037.00',
		indep_year: '1910',
		population: '40377000',
		life_expectancy: '51.1',
		gnp: '116729.00',
		gnp_old: '129092.00',
		local_name: 'South Africa',
		government_form: 'Republic',
		head_of_state: 'Thabo Mbeki',
		capital: '716',
		code_2: 'ZA',
	},
	{
		code: 'ZMB',
		name: 'Zambia',
		continent: Continent.Africa,
		region: 'Eastern Africa',
		surface_area: '752618.00',
		indep_year: '1964',
		population: '9169000',
		life_expectancy: '37.2',
		gnp: '3377.00',
		gnp_old: '3922.00',
		local_name: 'Zambia',
		government_form: 'Republic',
		head_of_state: 'Frederick Chiluba',
		capital: '3162',
		code_2: 'ZM',
	},
	{
		code: 'ZWE',
		name: 'Zimbabwe',
		continent: Continent.Africa,
		region: 'Eastern Africa',
		surface_area: '390757.00',
		indep_year: '1980',
		population: '11669000',
		life_expectancy: '37.8',
		gnp: '5951.00',
		gnp_old: '8670.00',
		local_name: 'Zimbabwe',
		government_form: 'Republic',
		head_of_state: 'Robert G. Mugabe',
		capital: '4068',
		code_2: 'ZW',
	},
];
