export const data = [
	{
		id: 19,
		name: 'AUDITORIA PH',
		description: null,
		state: true,
		creationDate: new Date(),
		modificationDate: new Date(),
		menu: [
			{ type: 'link', id: '1' },
			{ type: 'sub', id: '2', children: [{ id: '26' }] },
		],
	},
	{
		id: 17,
		name: 'CONDUCTOR',
		description: null,
		state: true,
		creationDate: new Date(),
		modificationDate: new Date(),
		menu: [],
	},
	{
		id: 21,
		name: 'AUDITORIA WILLARD',
		description: null,
		state: true,
		creationDate: new Date(),
		modificationDate: new Date(),
		menu: [],
	},
	{
		id: 14,
		name: 'PLANEADOR DE TRANSPORTE',
		description: null,
		state: true,
		creationDate: new Date(),
		modificationDate: new Date(),
		menu: [
			{ type: 'link', id: '1' },
			{ type: 'sub', id: '2', children: [{ id: '21' }] },
		],
	},
	{
		id: 15,
		name: 'WILLARD LOGISTICA',
		description: null,
		state: true,
		creationDate: new Date(),
		modificationDate: new Date(),
		menu: [
			{ type: 'link', id: '1' },
			{ type: 'sub', id: '2', children: [{ id: '23' }] },
		],
	},
	{
		id: 16,
		name: 'FABRICA BW',
		description: null,
		state: true,
		creationDate: new Date(),
		modificationDate: new Date(),
		menu: [
			{ type: 'link', id: '1' },
			{ type: 'sub', id: '2', children: [{ id: '22' }] },
		],
	},
	{
		id: 22,
		name: 'ADMINISTRATOR',
		description: 'Rol aplicado a los usuarios administrativos',
		state: true,
		creationDate: new Date(),
		modificationDate: new Date(),
		menu: [
			{ type: 'link', id: '1' },
			{
				type: 'sub',
				id: '3',
				children: [{ id: '31' }, { id: '32' }, { id: '33' }],
			},
			{
				type: 'sub',
				id: '4',
				children: [
					{ id: '41' },
					{ id: '42' },
					{ id: '43' },
					{ id: '44' },
					{ id: '45' },
					{ id: '46' },
					{ id: '47' },
					{ id: '48' },
					{ id: '49' },
					{ id: '410' },
					{ id: '411' },
					{ id: '412' },
					{ id: '413' },
					{ id: '414' },
					{ id: '415' },
					{ id: '416' },
					{ id: '417' },
					{ id: '418' },
					{ id: '419' },
					{ id: '420' },
					{ id: '421' },
				],
			},
		],
	},
	{
		id: 13,
		name: 'ASESOR PH',
		description: null,
		state: true,
		creationDate: new Date(),
		modificationDate: new Date(),
		menu: [
			{ type: 'link', id: '1' },
			{ type: 'sub', id: '2', children: [{ id: '22' }] },
		],
	},
	{
		id: 18,
		name: 'AGENCIA PH',
		description: null,
		state: true,
		creationDate: new Date(),
		modificationDate: new Date(),
		menu: [
			{ type: 'link', id: '1' },
			{
				type: 'sub',
				id: '2',
				children: [{ id: '22' }, { id: '24' }, { id: '25' }],
			},
		],
	},
	{
		id: 20,
		name: 'RECUPERADORA',
		description: null,
		state: true,
		creationDate: new Date(),
		modificationDate: new Date(),
		menu: [
			{ type: 'link', id: '1' },
			{ type: 'sub', id: '2', children: [{ id: '24' }] },
		],
	},
];

