export enum ErrorEnum {
	DEFAULT = '0: Error desconocido',
	SERVER_ERROR = '500: El servidor está ocupado, inténtelo de nuevo más tarde',

	SYSTEM_USER_EXISTS = '1001: El usuario del sistema ya existe',
	INVALID_VERIFICATION_CODE = '1002: Código de verificación inválido',
	INVALID_EMAIL_PASSWORD = '1003: Correo electronico o contraseña incorrectos',
	NODE_ROUTE_EXISTS = '1004: La ruta del nodo ya existe',
	PERMISSION_REQUIRES_PARENT = '1005: El permiso debe tener un nodo padre',
	ILLEGAL_OPERATION_DIRECTORY_PARENT = '1006: Operación no permitida: este nodo solo admite padres de tipo directorio',
	ILLEGAL_OPERATION_CANNOT_CONVERT_NODE_TYPE = '1007: Operación no permitida: no se puede convertir directamente el tipo de nodo',
	ROLE_HAS_ASSOCIATED_USERS = '1008: Este rol tiene usuarios asociados, elimine los usuarios asociados primero',
	DEPARTMENT_HAS_ASSOCIATED_USERS = '1009: Este departamento tiene usuarios asociados, elimine los usuarios asociados primero',
	DEPARTMENT_HAS_ASSOCIATED_ROLES = '1010: Este departamento tiene roles asociados, elimine los roles asociados primero',
	PASSWORD_MISMATCH = '1011: Las contraseñas no coinciden',
	LOGOUT_OWN_SESSION = '1012: Si desea cerrar la sesión actual, cierre sesión en la esquina superior derecha',
	NOT_ALLOWED_TO_LOGOUT_USER = '1013: No tiene permiso para cerrar la sesión de este usuario',
	PARENT_MENU_NOT_FOUND = '1014: Menú principal no encontrado',
	DEPARTMENT_HAS_CHILD_DEPARTMENTS = '1015: Este departamento tiene subdepartamentos, elimine los subdepartamentos primero',
	SYSTEM_BUILTIN_FUNCTION_NOT_ALLOWED = '1016: No se permite la operación de funciones integradas del sistema',
	USER_NOT_FOUND = '1017: Usuario no encontrado',
	UNABLE_TO_FIND_DEPARTMENT_FOR_USER = '1018: No se puede encontrar el departamento al que pertenece el usuario actual',
	DEPARTMENT_NOT_FOUND = '1019: Departamento no encontrado',
	DICT_NAME_EXISTS = '1020: Ya existe un diccionario con el mismo nombre',
	PARAMETER_CONFIG_KEY_EXISTS = '1021: La clave de configuración de parámetros ya existe',
	DEFAULT_ROLE_NOT_FOUND = '1022: El rol predeterminado asignado no se encuentra',
	SYSTEM_ROLE_EXISTS = '1023: El rol del sistema ya existe',
	SYSTEM_WEB_EXISTS = '1024: El sitio web ya existe',
	SYSTEM_WEB_NOT_EXISTS = '1025: El sitio web no existe',

	INVALID_LOGIN = '1101: Inicio de sesión no válido, vuelva a iniciar sesión',
	NO_PERMISSION = '1102: Sin permisos para acceder',
	ONLY_ADMIN_CAN_LOGIN = '1103: Solo los administradores pueden iniciar sesión',
	REQUEST_INVALIDATED = '1104: La solicitud actual ha caducado',
	ACCOUNT_LOGGED_IN_ELSEWHERE = '1105: Su cuenta ha iniciado sesión en otro lugar',
	GUEST_ACCOUNT_RESTRICTED_OPERATION = '1106: La cuenta de invitado no permite esta operación',
	REQUESTED_RESOURCE_NOT_FOUND = '1107: El recurso solicitado no se encuentra',

	TOO_MANY_REQUESTS = '1201: Demasiadas solicitudes, espere un minuto antes de intentarlo nuevamente',
	MAXIMUM_FIVE_VERIFICATION_CODES_PER_DAY = '1202: Máximo de 5 códigos de verificación por día',
	VERIFICATION_CODE_SEND_FAILED = '1203: Fallo al enviar el código de verificación',

	INSECURE_MISSION = '1301: Misión insegura, asegúrese de que la ejecución esté anotada con @Mission',
	EXECUTED_MISSION_NOT_FOUND = '1302: Misión ejecutada no encontrada',
	MISSION_EXECUTION_FAILED = '1303: Fallo en la ejecución de la misión',
	MISSION_NOT_FOUND = '1304: Misión no encontrada',

	// Relacionado con OSS
	OSS_FILE_OR_DIR_EXIST = '1401: El archivo o directorio que intenta crear ya existe',
	OSS_NO_OPERATION_REQUIRED = '1402: No se requiere ninguna operación',
	OSS_EXCEE_MAXIMUM_QUANTITY = '1403: Se ha superado la cantidad máxima permitida',
}
