export enum ROL {
	'AUDITORIA_PH' = 19,
	'CONDUCTOR' = 17,
	'AUDITORIA_WILLARD' = 21,
	'PLANEADOR_TRANSPORTE' = 14,
	'WILLARD_LOGISTICA' = 15,
	'FABRICA_BW' = 16,
	'ADMINISTRATOR' = 22,
	'ASESOR_PH' = 13,
	'AGENCIA_PH' = 18,
	'RECUPERADORA' = 20,
	'TODOS' = 0,
}
