// "ESTADO_RUTA"
export enum ROUTE_STATE {
	'CONFIRMED' = 46, // 'CONFIRMADO',
	'CLOSED' = 47, // 'CERRADA'
}

// "SOLICITUD_ESTADO"
export enum REQUEST_STATUS {
	'PENDING' = 61, // 'PENDIENTE',
	'CONFIRMED' = 62, // 'CONFIRMADO',
	'REJECTED' = 63, // 'RECHAZADO',
	'CANCELLED' = 64, // 'CANCELADO',
	'FOLLOW_UP' = 65, // 'SEGUIMIENTO',
	'INCOMPLETE' = 66, // 'INCOMPLETA',
}

// "RECEPCION_ESTADO"
export enum RECEIPT_STATUS {
	REGISTERED = 67, // 'REGISTRADO'
}

// "AUDITORIA_GUIA_ESTADO"
export enum AUDIT_GUIDE_STATUS {
	'WITHOUT_GUIDE' = 101, // "SIN GUIA",
	'BY_CONCILLIATE' = 102, // "PENDIENTE",
	'CONFIRMED' = 103, // "CONFIRMADO",
	'TRANSIT' = 104 // "EN TRANSITO"
}
