// "ESTADO_RUTA"
export enum ROUTE_STATE {
	'CONFIRMED' = 46, // 'CONFIRMADO',
	'CLOSED' = 47, // 'CERRADA'
}

// "SOLICITUD_ESTADO"
export enum REQUEST_STATUS {
	'PENDING' = 61, // 'PENDIENTE',
	'CONFIRMED' = 62, // 'CONFIRMADO',
	'REJECTED' = 63, // 'RECHAZADO',
	'CANCELLED' = 64, // 'CANCELADO',
	'FOLLOW_UP' = 65, // 'SEGUIMIENTO',
	'INCOMPLETE' = 66, // 'INCOMPLETA',
}

// "RECEPCION_ESTADO"
export enum RECEIPT_STATUS {
	REGISTERED = 67, // 'REGISTRADO'
}

// "AUDITORIA_RUTA_ESTADO"
export enum AUDIT_ROUTE_STATUS {
	'WITHOUT_ROUTE' = 101, // "SIN GUIA",
	'BY_CONCILLIATE' = 102, // "POR CONCILIAR",
	'CONFIRMED' = 103, // "CONFIRMADO",
	'TRANSIT' = 104 // "EN TRANSITO"
}

// "AUDITORIA_RUTA_RAZON"
export enum AUDIT_ROUTE_REASON {
	'RECOVERY' = 'R', // "RECUPERADORA",
	'TRANSPORTER' = 'T', // "TRANSPORTADORA",
	'BOTH' = 'B', // "AMBOS",
	'NONE' = 'N' // "NINGUNO"
}
