export enum ROUTE_STATE {
	'CONFIRMED' = 'CONFIRMADO',
	'CLOSED' = 'CERRADA'
}

export enum REQUEST_STATUS {
	'PENDING' = 'PENDIENTE',
	'CONFIRMED' = 'CONFIRMADO',
	'REJECTED' = 'RECHAZADO',
	'CANCELLED' = 'CANCELADO',
	'FOLLOW-UP' = 'SEGUIMIENTO',
	'INCOMPLETE' = 'INCOMPLETA',
}

export enum RECEIPT_STATUS {
	REGISTERED = 'REGISTRADO'
}

export enum AUDIT_GUIDE_STATUS {
	'WITHOUT GUIDE' = "SIN GUIA",
	'PENDING' = "PENDIENTE",
	'CONFIRMED' = "CONFIRMADO",
}
