// "TIPO_LUGAR_RECOGIDA"
export enum PICKUP_LOCATION_TYPE {
	DIRECT_CUSTOMER = 50,  // "CLIENTE_DIRECTO"
	DEPARTMENT_STORES = 51, // "GRANDES SUPERFICIES"
	AGENCY = 52,  // "AGENCIA"
	FACTORY = 53,  // "FÁBRICA"
	CENTER = 21,  // "CENTRO"
}
