export const dataParent = [
	{
		id: 1,
		code: 'PAIS',
		name: 'PAISES',
		description: 'PAIES',
		isActive: true,
		createdBy: null,
		updatedBy: null,
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 2,
		code: 'DEPARTAMENTO',
		name: 'DEPARTAMENTOS',
		description: 'DEPARTAMENTOS',
		isActive: true,
		createdBy: null,
		updatedBy: null,
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 3,
		code: 'CIUDAD',
		name: 'CIUDADES',
		description: 'CIUDADES',
		isActive: true,
		createdBy: null,
		updatedBy: null,
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 4,
		code: 'TIPOS_SEDES_ACOPIO',
		name: 'TIPOS SEDES ACOPIO',
		description: null,
		isActive: true,
		createdBy: null,
		updatedBy: null,
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 5,
		code: 'TIPO_LUGAR_RECOGIDA',
		name: 'TIPO LUGAR DE RECOGIDA',
		description: null,
		isActive: true,
		createdBy: null,
		updatedBy: null,
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 6,
		code: 'TIPO_DOCUMENTO',
		name: 'TIPO DOCUMENTO',
		description: null,
		isActive: true,
		createdBy: null,
		updatedBy: null,
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 7,
		code: 'TIPO_PRODUCTO',
		name: 'TIPO PRODUCTO',
		description: null,
		isActive: true,
		createdBy: null,
		updatedBy: null,
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 8,
		code: 'TIPO_GUIA',
		name: 'TIPO GUÍA',
		description: null,
		isActive: true,
		createdBy: null,
		updatedBy: null,
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 9,
		code: 'TIPO_EVIDENCIA',
		name: 'TIPO EVIDENCIA',
		description: null,
		isActive: true,
		createdBy: null,
		updatedBy: null,
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 10,
		code: 'UNIDAD_MEDIDA',
		name: 'UNIDAD DE MEDIDA',
		description: null,
		isActive: true,
		createdBy: null,
		updatedBy: null,
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 11,
		code: 'ZONA',
		name: 'ZONA',
		description: null,
		isActive: true,
		createdBy: null,
		updatedBy: null,
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 12,
		code: 'TIPO_CAMION',
		name: 'TIPO CAMIÓN',
		description: null,
		isActive: true,
		createdBy: null,
		updatedBy: null,
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 13,
		code: 'ESTADO_RUTA',
		name: 'ESTADO RUTA',
		description: null,
		isActive: true,
		createdBy: null,
		updatedBy: null,
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 14,
		code: 'TIPO_CLIENTE',
		name: 'TIPO CLIENTE',
		description: null,
		isActive: true,
		createdBy: null,
		updatedBy: null,
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 15,
		code: 'MOTIVO_ESPECIAL',
		name: 'MOTIVO ESPECIAL',
		description: null,
		isActive: true,
		createdBy: null,
		updatedBy: null,
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 16,
		code: 'SOLICITUD_ESTADO',
		name: 'SOLICITUD ESTADO',
		description: 'ESTADOS DE LAS SOLICITUDES DE RECOGIDA',
		isActive: true,
		createdBy: null,
		updatedBy: null,
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 17,
		code: 'RECEPCION_ESTADO',
		name: 'RECEPCIÓN ESTADO',
		description: 'ESTADOS DE LAS RECEPCIONES DE RECOGIDA',
		isActive: true,
		createdBy: null,
		updatedBy: null,
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 18,
		code: 'AUDITORIA_GUIA_ESTADO',
		name: 'AUDITORIA GUIA ESTADO',
		description: 'ESTADOS DE LAS AUDITORIAS DE GUIAS',
		isActive: true,
		createdBy: null,
		updatedBy: null,
		createdAt: new Date(),
		updatedAt: new Date()
	}
];

export const dataChild = [
	{
		id: 84,
		parentId: 1,
		catalogCode: "PAIS",
		name: "GRECIA",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 85,
		parentId: 2,
		catalogCode: "DEPARTAMENTO",
		name: "ANTIOQUIA",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 86,
		parentId: 3,
		catalogCode: "CIUDAD",
		name: "MEDELLIN",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 88,
		parentId: 3,
		catalogCode: "CIUDAD",
		name: "BARANOA",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 89,
		parentId: 3,
		catalogCode: "CIUDAD",
		name: "SABANALARGA",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 90,
		parentId: 3,
		catalogCode: "CIUDAD",
		name: "SUAN",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 91,
		parentId: 3,
		catalogCode: "CIUDAD",
		name: "SABANAGRANDE",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 93,
		parentId: 3,
		catalogCode: "CIUDAD",
		name: "RIO FRIO",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 95,
		parentId: 7,
		catalogCode: "TIPO_PRODUCTO",
		name: "COBRE",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 97,
		parentId: 11,
		catalogCode: "ZONA",
		name: "ZONA PRUEBA",
		description: "prueba",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 99,
		parentId: 10,
		catalogCode: "UNIDAD_MEDIDA",
		name: "GR",
		description: "GRAMO",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 56,
		parentId: 1,
		catalogCode: "TIPO_CLIENTE",
		name: "OTROS SITIOS",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 57,
		parentId: 56,
		catalogCode: "TIPO_CLIENTE",
		name: "FÁBRICA",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 3,
		parentId: 6,
		catalogCode: "TIPO_DOCUMENTO",
		name: "CC",
		description: "Cedula de Ciudadania",
		order: null,
		status: true,
		extra1: "NULL",
		extra2: "NULL",
		extra3: "NULL",
		extra4: "NULL",
		extra5: "NULL",
	},
	{
		id: 23,
		parentId: 10,
		catalogCode: "UNIDAD_MEDIDA",
		name: "KG",
		description: "Kilogramo",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 1,
		parentId: 1,
		catalogCode: "PAIS",
		name: "COLOMBIA",
		description: "pais colombia",
		order: 1,
		status: true,
		extra1: "string",
		extra2: "string",
		extra3: "string",
		extra4: "string",
		extra5: "string",
	},
	{
		id: 2,
		parentId: 1,
		catalogCode: "PAIS",
		name: "VENEZUELA",
		description: "Pais Venezuela",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 59,
		parentId: 56,
		catalogCode: "MOTIVO_ESPECIAL",
		name: "RUTA NO DEFINIDA",
		description: "motivo de ruta no definida",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 58,
		parentId: 56,
		catalogCode: "MOTIVO_ESPECIAL",
		name: "VOLUMEN (> 700)",
		description: "motivo volumen mayor a 700",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 18,
		parentId: 2,
		catalogCode: "DEPARTAMENTO",
		name: "ATLANTICO",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 19,
		parentId: 1,
		catalogCode: "CIUDAD",
		name: "BARRANQUILLA",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 20,
		parentId: 1,
		catalogCode: "TIPOS_SEDES_ACOPIO",
		name: "TIPO SMALL",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 25,
		parentId: 1,
		catalogCode: "TIPO_GUIA",
		name: "GUIAS ALFA",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 26,
		parentId: 1,
		catalogCode: "TIPO_EVIDENCIA",
		name: "FOTOGRAFICO",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 36,
		parentId: 1,
		catalogCode: "PAIS",
		name: "ECUADOR",
		description: "pais ecuador",
		order: 0,
		status: false,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 37,
		parentId: 1,
		catalogCode: "ZONA",
		name: "NORTE",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 38,
		parentId: 1,
		catalogCode: "ZONA",
		name: "SUR",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 39,
		parentId: 1,
		catalogCode: "ZONA",
		name: "ORIENTE",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 40,
		parentId: 1,
		catalogCode: "ZONA",
		name: "OCCIDENTE",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 41,
		parentId: 1,
		catalogCode: "TIPO_CAMION",
		name: "C1",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 42,
		parentId: 1,
		catalogCode: "TIPO_CAMION",
		name: "C2",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 43,
		parentId: 1,
		catalogCode: "TIPO_CAMION",
		name: "C3",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 44,
		parentId: 1,
		catalogCode: "TIPO_CAMION",
		name: "C4",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 45,
		parentId: 1,
		catalogCode: "TIPO_CAMION",
		name: "C5",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 46,
		parentId: 1,
		catalogCode: "ESTADO_RUTA",
		name: "CONFIRMADA",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 47,
		parentId: 1,
		catalogCode: "ESTADO_RUTA",
		name: "CERRADA",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 48,
		parentId: 1,
		catalogCode: "TIPOS_SEDES_ACOPIO",
		name: "RECUPERADORA",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 49,
		parentId: 1,
		catalogCode: "TIPOS_SEDES_ACOPIO",
		name: "AGENCIA",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 50,
		parentId: 1,
		catalogCode: "TIPO_LUGAR_RECOGIDA",
		name: "CLIENTE DIRECTO",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 51,
		parentId: 1,
		catalogCode: "TIPO_LUGAR_RECOGIDA",
		name: "GRANDES SUPERFICIES",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 52,
		parentId: 1,
		catalogCode: "TIPO_LUGAR_RECOGIDA",
		name: "AGENCIA",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 53,
		parentId: 1,
		catalogCode: "TIPO_LUGAR_RECOGIDA",
		name: "FÁBRICA",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 54,
		parentId: 1,
		catalogCode: "TIPO_CLIENTE",
		name: "GRANDES SUPERFICIES",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 55,
		parentId: 1,
		catalogCode: "TIPO_CLIENTE",
		name: "AGENCIA",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 60,
		parentId: 56,
		catalogCode: "MOTIVO_ESPECIAL",
		name: "CAMBIO DESTINO",
		description: "MOTIVO CAMBIO DESTINO",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 61,
		parentId: 16,
		catalogCode: "SOLICITUD_ESTADO",
		name: "PENDIENTE",
		description: "ESTADO DE SOLICITUD DE RECOGIDA - Pendiente",
		order: null,
		status: true,
		extra1: "NULL",
		extra2: "NULL",
		extra3: "NULL",
		extra4: "NULL",
		extra5: "NULL",
	},
	{
		id: 62,
		parentId: 16,
		catalogCode: "SOLICITUD_ESTADO",
		name: "CONFIRMADO",
		description: "ESTADO DE SOLICITUD DE RECOGIDA - Confirmado",
		order: null,
		status: true,
		extra1: "NULL",
		extra2: "NULL",
		extra3: "NULL",
		extra4: "NULL",
		extra5: "NULL",
	},
	{
		id: 63,
		parentId: 16,
		catalogCode: "SOLICITUD_ESTADO",
		name: "RECHAZADO",
		description: "ESTADO DE SOLICITUD DE RECOGIDA - Rechazado",
		order: null,
		status: true,
		extra1: "NULL",
		extra2: "NULL",
		extra3: "NULL",
		extra4: "NULL",
		extra5: "NULL",
	},
	{
		id: 64,
		parentId: 16,
		catalogCode: "SOLICITUD_ESTADO",
		name: "CANCELADO",
		description: "ESTADO DE SOLICITUD DE RECOGIDA - Cancelado",
		order: null,
		status: true,
		extra1: "NULL",
		extra2: "NULL",
		extra3: "NULL",
		extra4: "NULL",
		extra5: "NULL",
	},
	{
		id: 65,
		parentId: 16,
		catalogCode: "SOLICITUD_ESTADO",
		name: "SEGUIMIENTO",
		description: "ESTADO DE SOLICITUD DE RECOGIDA - Seguimiento",
		order: null,
		status: true,
		extra1: "NULL",
		extra2: "NULL",
		extra3: "NULL",
		extra4: "NULL",
		extra5: "NULL",
	},
	{
		id: 66,
		parentId: 16,
		catalogCode: "SOLICITUD_ESTADO",
		name: "INCOMPLETA",
		description: "ESTADO DE SOLICITUD DE RECOGIDA - Incompleta",
		order: null,
		status: true,
		extra1: "NULL",
		extra2: "NULL",
		extra3: "NULL",
		extra4: "NULL",
		extra5: "NULL",
	},
	{
		id: 67,
		parentId: 17,
		catalogCode: "RECEPCION_ESTADO",
		name: "REGISTRADO",
		description: "ESTADO DE SOLICITUD DE RECOGIDA - Registrado",
		order: null,
		status: true,
		extra1: "NULL",
		extra2: "NULL",
		extra3: "NULL",
		extra4: "NULL",
		extra5: "NULL",
	},
	{
		id: 73,
		parentId: 1,
		catalogCode: "PAIS",
		name: "PERU",
		description: "país peru",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 24,
		parentId: 7,
		catalogCode: "TIPO_PRODUCTO",
		name: "BUPAS",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 72,
		parentId: 7,
		catalogCode: "TIPO_PRODUCTO",
		name: "OTROS MATERIALES",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 83,
		parentId: 11,
		catalogCode: "ZONA",
		name: "ZONA 3",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 74,
		parentId: 1,
		catalogCode: "PAIS",
		name: "ARGENTINA",
		description: "Pais Argentina",
		order: 0,
		status: false,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 75,
		parentId: 2,
		catalogCode: "DEPARTAMENTO",
		name: "MAGDALENA",
		description: "departamento Magdalena",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 76,
		parentId: 3,
		catalogCode: "CIUDAD",
		name: "SANTA MARTA",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 78,
		parentId: 8,
		catalogCode: "TIPO_GUIA",
		name: "GUIAS BETA",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 21,
		parentId: 1,
		catalogCode: "TIPO_LUGAR_RECOGIDA",
		name: "CENTRO",
		description: "observaciones",
		order: 0,
		status: false,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 79,
		parentId: 5,
		catalogCode: "TIPO_LUGAR_RECOGIDA",
		name: "FABRICA1",
		description: "fabrica1",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 80,
		parentId: 2,
		catalogCode: "DEPARTAMENTO",
		name: "AS",
		description: "d",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 81,
		parentId: 11,
		catalogCode: "ZONA",
		name: "ZONA 1",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 82,
		parentId: 11,
		catalogCode: "ZONA",
		name: "ZONA 2",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 87,
		parentId: 4,
		catalogCode: "TIPOS_SEDES_ACOPIO",
		name: "PRUEBA",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 92,
		parentId: 3,
		catalogCode: "CIUDAD",
		name: "CIENAGA",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 94,
		parentId: 6,
		catalogCode: "TIPO_DOCUMENTO",
		name: "NIT",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 96,
		parentId: 11,
		catalogCode: "ZONA",
		name: "ZONA ROJA",
		description: "pruebas jeitson",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 98,
		parentId: 11,
		catalogCode: "ZONA",
		name: "ZONA AZUL",
		description: "",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	},
	{
		id: 100,
		parentId: 12,
		catalogCode: "TIPO_CAMION",
		name: "C6",
		description: "camion c6",
		order: 0,
		status: true,
		extra1: "",
		extra2: "",
		extra3: "",
		extra4: "",
		extra5: "",
	}
];
