name: Build and deploy Node.js app to Azure Web App - api-willard

on:
  push:
    branches:
      - branch-test
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install and build
        run: |
          npm install
          npm run build --if-present

      - name: Verify artifact contents
        run: ls -R  # Imprime la estructura de directorios para asegurarte de que el build esté en la ruta esperada

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app  # Verifica que este nombre sea el mismo en la descarga
          path: |
            ./dist  # Asegúrate de que esta carpeta existe y tiene contenido
            README.md  # Archivo adicional para verificar la subida
          if-no-files-found: error  # Asegura que falle si no encuentra archivos

      - name: Check if artifact was uploaded
        run: echo "Artifact node-app uploaded successfully."

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app  # Este nombre debe coincidir con el utilizado en la subida

      - name: Verify downloaded contents
        run: ls -R  # Verifica que los archivos se descargaron correctamente

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'api-willard'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AD1AFF332A4B48E2810D80C8F1150DDB }}
